yodaos-project/yoda.js

modules/player/src/PlayWrap.cc

When it calls `stop()` and the low-level player still notifies, it would crash.

player: fix if the player has been stoped to continue got notified

---

apps/bluetooth/app.js

ISSUE: When listening cloud news, turn on bluetooth. After device connnected with a phone, the news app will be stopped.
ROOT CAUSE: Bluetooth event will call tts.speak with impatient = true, which will return immediately. And original design will continue call setBackground(), thus the news app will be resume at once. After tts received bluetooth's speak request, the news app's tts will be stopped.
SOLUTION: Change tts.speak with impatient = false, to avoid collision with other app's tts.

bluetooth: change tts.speak impatient param

---

test/@yoda/flora/flora.test.js

This fixes the CI hang up at https://ci.rokid.com/view/Yodaos/job/rokid-ci-yodart-unit-tests/74/ which takes almost 30 minutes to run and failed.
/cc @mingzc0508 @cheongwen

flora, test: set the timeout for flora loop tests

---

apps/cloudappclient/app.js

This patch fixes the problem that the alarm reminder failed.

fixed(cloudappclient): native directives should not preempt cloudappclient

---

apps/alarm/alarm-core.js
apps/alarm/expression.js
apps/alarm/node-cron.js

fix alram bugs
1. Month error: it will endless loop when now is on December.
2. It should not combine all tts in queue.
- [ alarm-core ] add clear before alarm start. It should clear prev alarm when alarm is breaked.
- [ node-cron ] update `combineReminderTts`. it should not combine all tts in queue, just combine tts with same time.
- [ expression ] In JS, `getMonth` return 0 - 11, It will be endless loop when now is on December.

alarm: fix month error

---

LICENSE.md

Follow normal apache-2.0 license formats to enable GitHub and other tools license detection.

Normalize license

---

runtime/lib/component/custodian.js

When the network is disconnected and no history found(commonly the unbind operation), this reset the network state(includes welcome and lifetime) before network app is started.

custodian: reset network if no history found

---

packages/@yoda/light/src/LightNative.cc

A breaking change has been introduced to LumenLight interface at https://openai-corp.rokid.com/#/c/11905/.
/cc @shiwf

light: fix build error on breaking change of native light api

---

runtime/lib/app-runtime.js
runtime/lib/component/lifetime.js
test/runtime/lifetime/on-evict.test.js
test/runtime/lifetime/stack-manipulation.test.js

- fix duplicated emit of `eviction` event on evicting cut app.
- add new event `preemption` on app been preempted.

lifetime: duplicated emit of eviction

---

etc/env.json
etc/openvoice-sdk.json
runtime/lib/component/flora.js

remove speech config params from env.json
add speech/tts config params at openvoice-sdk.json

add config file for speech/tts config

---

packages/@yoda/bluetooth/a2dp.js

The old opportunity of doing copy status is after emit event, then if event handler query status, the status will be wrong.

bluetooth: correct the opportunity of copy updated status.

---

etc/component-config.json
runtime/lib/component/custodian.js
runtime/lib/component/dispatcher.js
runtime/lib/component/turen.js
test/runtime/dispatcher/index.test.js
test/testsets.txt

A working draft for #183.
Interception interest has to be pre-defined in a configuration file in order to declare priorities of interceptors.
With interception interest claimed, once a event with interest is sent to dispatcher, interceptors have to respond to the event and determines if it is the time to prevent default behavior of the event. Anything truthy value returned would be treated as interest of delegating the event to the interceptor. Or a falsy value should be returned in event handler to indicate there is nothing to do.

component: event interception dispatcher

---

runtime/lib/descriptor/activity-descriptor.js
runtime/lib/descriptor/httpgw-descriptor.js
runtime/lib/descriptor/index.js

this module provides the following methods:
- getSign()
- request(path, data)
And this improve #147 and #154, and also deprecates the `activity.get()` for #110.

descriptor: add new httpgw module

---

etc/component-config.json
runtime/lib/app-runtime.js
runtime/lib/component/dbus-registry.js
runtime/lib/component/dispatcher.js
runtime/lib/component/ota.js
runtime/lib/component/turen.js
test/runtime/dispatcher/index.test.js

Allow components to accept a delegation asynchronously.

dispatcher: async delegation

---

packages/@yoda/bluetooth/a2dp.js
packages/@yoda/flora/comp.js

if fid not string, don't plus '#' after uri string
flora client of bluetooth-a2dp will not use fid

fix bug for flora comp.js

---

runtime/lib/app-runtime.js
runtime/lib/component/app-loader.js

This notifies when the device is connected to the network, developers
could start to report a heartbeat, fetch a request.
Note that, if your request expected the httpgw or logged in state, you
should wait for "on-ready".

runtime: add "on-connected" notification

---

runtime/client/translator-ipc.js
runtime/lib/app/ext-app.js
test/fixture/ext-app/app.js
test/runtime/ext-app.test.js

ext-app: extra properties of error object on rejection

---

runtime/services/otad/index.js
runtime/services/otad/otad

If new updates are published during downloading, currently downloading should be terminated and begin new OTA.
In the implementation, otad script forces `/usr/yoda/services/otad/index.js` to exit every 30 minutes if it is still running and restart it to achieve a force recheck on if new update available.

otad: force check new updates by interval

---

packages/@yoda/httpsession/src/httpsession.cc

Every HttpSessionAsyncTask instance was released at the moment of HTTP request finished, before handling response in main thread.

httpsession: prematurely releases of httpsession tickets

---

test/testsets.txt

The above module tests failed on current CI, let's just skip it for now.

build: disable trace/httpsession tests

---

runtime/services/vuid/index.js

Currently the module loading(require) blocks all the former I/O callbacks and timers. This causes that watchdog is always blocked and trigger the reboot action.
This patch starts watchdog after the module loading, and the runtime is initialized.

bootstrap: start watchdog when runtime is ready

---

apps/log-switch/app.js
packages/logger/index.js
test/logger/simple.test.js

when there are 300K logs dumped in 30s
- the average CPU usage of logd is 3%
- the average CPU usage of log2cloud is 2%, occasionally jump to 5% (maybe uploading?)

logger: add log level switch timeout

---

packages/@yoda/bluetooth/a2dp.js
packages/@yoda/bluetooth/helper.js

1. correct flora destruct function name.
2. fix disconnect command name.

bluetooth: fix flora destruct function name.

---

runtime/lib/app-runtime.js

It fixes the first interaction after playing the welcome audio, when the daemon applications are not ready, and it delays the following 2 actions:
- The playing welcome audio
- The delegation for `runtimeDidLogin`

runtime: welcome audio playing should wait for daemon apps started

---

apps/bluetooth/app.js

According PRD v1.3, should not close bluetooth while close app.

bluetooth: only disconnect but not close bluetooth.

---

runtime/lib/component/turen.js

Fixes issues brought in #237. 
Media controlled by scene app would not be recovered on end of waking up.

turen: closing pickup while waking up shall not discard next event

---

apps/bluetooth/app.js

a2dp.disconnect() supports disconnect all profiles by one command.

bluetooth: remove hfp disconnect

---

packages/@yoda/bluetooth/a2dp.js

Change flora msg to instant mode to avoid received old cached wrong state.

bluetooth: change flora msg to instant mode

---

packages/@yoda/bluetooth/a2dp.js
packages/@yoda/bluetooth/hfp.js

1. Add syncVol() in a2dp.
2. Add unified getXxxxState() interfaces() for upper layer.
3. Bind hands-free profile's open & close with a2dp.

bluetooth: add syncVol function and unified getXxxxState interfaces

---

packages/@yoda/audio/index.js
packages/@yoda/flora/disposable.js
tools/helper/flora-listener.js

While lots of processes would like to set volume by their own side, some apps would like to listen on changes on the volume to sync volume between devices.

audio: broadcast volume change on setVolume

---

runtime/lib/app/ext-app.js
runtime/lib/component/app-scheduler.js

Occasionally apps may have no time to execute termination procedures.

ext-app: delaying process termination on ext-app

---

apps/timer/RKDownTimer.js
apps/timer/RKTime.js

BF: #18314 - When set multiple timer, the time is not accuracy.

timer: reset time before parse time from nlp

---

packages/@yoda/trace/index.js
test/@yoda/trace/index.test.js

Still not start the test for tracing, `httpsession` opens an async handle at module initializer, that causes the runner suspend, the following are that local result:
```
[INFO] tryStart 1 (nil)
[INFO] return isRunning 1 0x429ac0
[INFO] selectRoutine
[INFO] 0x415690 mMultiHandle 0x7f780008c0
TAP version 13
ok 1 expect an array on traces
ok 2 expect traces length greater than 0
[INFO] tryStart 1 0x429ac0
[INFO] return ticket 0x430570 https://das-tc-service-pro.rokid.com/das-tracing-collection/tracingUpload
1..2
```

trace: no need to call .end() for httpsession

---

runtime/client/translator-ipc.js
runtime/lib/component/custodian.js
test/runtime/custodian/state-shift.test.js

custodian: enforced appScheduler dependency

---

runtime/lib/app-runtime.js

runtime: carrierId should be nil on non-triggered voice command

---

packages/@yoda/util/deprecate.js
runtime/lib/app-runtime.js
runtime/lib/cloudapi/index.js
runtime/lib/component/custodian.js
runtime/lib/component/dbus-registry.js
runtime/lib/descriptor/activity-descriptor.js
runtime/lib/descriptor/httpgw-descriptor.js
test/activity/ext-app-activity-api.test.js
test/component/custodian/state-shift.test.js
test/descriptor/httpgw.test.js

Migrate to a more statical way of getting a copy of credential.

runtime: deprecate onGetPropAll

---

runtime/lib/descriptor/activity-descriptor.js
test/descriptor/activity/exit.test.js
test/descriptor/activity/fixture/ext-app/app.js
test/descriptor/activity/fixture/ext-app/package.json

Fixes an issue(introduced by #417) that an unexpected error was thrown on app exiting with no options.

test: activity.exit

---

runtime/lib/component/turen.js

When user enter the pickup state manually, like the keyboard or confirm, we should disable the awaken engine at that time.

turen: toggle the engine when pickup

---

packages/@yodaos/application/context-manager.js
test/@yodaos/application/context-manager.test.js

If app was destroyed by VUI proactively rather than by app it self, contexts would preserve in memo.

context-manager: clears contexts on activity destroy

---

CODEOWNERS
packages/@yoda/ota/OWNERS
runtime/client/OWNERS
runtime/lib/app/OWNERS
runtime/lib/cloudapi/OWNERS
runtime/lib/component/OWNERS
runtime/services/lightd/OWNERS
runtime/services/multimediad/OWNERS
runtime/services/otad/OWNERS
runtime/services/ttsd/OWNERS
runtime/services/vuid/OWNERS
tools/OWNERS

To enable github automatically requesting reviews from certain maintainers, CODEOWNERS file declares who are responsible for reviewing the changes with a blob pattern.
ref#1: https://github.blog/2017-07-06-introducing-code-owners/
ref#2: https://help.github.com/articles/about-code-owners/

meta: code owners

---

apps/bluetooth/app.js

To fix random bugs which caused by death of bluetooth app.

bluetooth: set keepAlive in 'active' lifetime to force alive

---

packages/@yoda/bolero/loader.js
runtime/lib/component/keyboard.js
test/component/keyboard/descriptor.test.js

Enables convenience configurations to invoking component method.
Example config:
```json
{
"113": {
"click": {
"componentMethod": "turen.toggleMute",
"params": []
}
}
```

keyboard: component method support

---

runtime/lib/dbus-remote-call.js

When a name owner changes, signal filter should be re-aligned to the new names.
Fixes:
- https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18496
- https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18579
References:
- https://dbus.freedesktop.org/doc/dbus-java/api/org/freedesktop/DBus.NameOwnerChanged.html

dbus: re-listen dbus signals on name owner changed

---

.gitattributes

Attribute `eol` should only be applied to plain text files.

chore: treat all *.ogg files as binary

---

runtime/lib/app-runtime.js
test/runtime/init/index.test.js
test/runtime/rt-helper.js
test/runtime/voice-command.test.js
test/testsets.txt

Also fixes missing of guide/boot announcements.

test: runtime guide/boot announcements

---

apps/alarm/alarm-core.js
apps/alarm/app.js
apps/alarm/package.json

Exit alarm to save memory about 2M when there is no alarms and reminders. 
Update:
1. When device was restarted, get alarm's data only once.
2. If no alarms and reminders, exit alarm. When u create new alarms or reminders, alarm will be created.

exit alarm if no alarms and reminders

---

test/component/turen/lifetime.test.js

test(turen): resume scene app if cut app exited while still woken up

---

apps/cloudappclient/app.js
apps/cloudappclient/eventRequestMap.json
runtime/lib/descriptor/multimedia-descriptor.js
runtime/services/multimediad/index.js
runtime/services/multimediad/service.js

This PR contain following change:
1. Send a seekcomplete event to the cloud in order to synchronize progress
2. change the type of multimediad's event from string to number

cloudappclient: upload `seekcomplete` event to cloud

---

runtime/lib/component/light.js
runtime/services/lightd/flora.js

Lightd will waiting for `rokid.turen.end_voice` event to stop lights, so don't have to close it manually.
This pr depends on a patch in product_me.

fixed: setPickup.js should be waiting for event 'rokid.turen.end_voice'

---

apps/network/app.js
runtime/lib/app-runtime.js
runtime/lib/component/custodian.js

This PR contain following change:
1. Stop network configuration when key PowerActivation pressed

network: stop configuration when key PowerActivation pressed

---

runtime/lib/component/dnd-mode.js

Change-Id: I4fde035abdac0bdd37d982b8c1a9e2893d13b261
DND Mode needs to save the system volume, then set the dnd mode volume when the system is entering dnd-mode, but we will get the volumeChanged notify after the dnd-mode volume set.
So we need to set this flag, and ignore the first notify.

dnd-mode: add volume notify flag for component.dndmode

---

apps/custom-config/app.js
apps/custom-config/base-config.js
apps/custom-config/standby-light.js
etc/yoda/component-config.json
runtime/lib/app-runtime.js
runtime/lib/component/custom-config.js
test/component/custom-config/custom-config.test.js

add reload request for custom-config
add test
Change-Id: Ic8fc98d95788af7089ecdc1f06aba3753c3b2ac1
Custom config needs to be reloaded after system wakeup, so the app `customConfig` adds the new request `reload`, and the component `customConfig` adds the delegate `runtimeDidWakeup`.

custom-config: add delegate runtimeDidWakeup

---

apps/cloudappclient/app.js

when media cancel or error in cloudapp client,must sent  itemId duration and progress to server

Fix bug (18770)when media cancel or error in cloudapp client,must sent itemId duration and progress to server

---

apps/bluetooth/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18875

bluetooth: correct app type after disconnected

---

runtime/lib/component/battery.js
test/component/battery/index.test.js

Related https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18574
Actually apps would not be opened since dispatcher guarded no apps could be opened through it on hibernation.

battery: battery info should be memorized regardless of if hibernated

---

apps/alarm/app.js

Alarm add unhandled rejection.
Scene: When the alarm starts, it uses 'setForeground' method to be the first level, it will execute some 'js' operations, then play media. If now one progress will be executed, it will strip priority from alarm, then the media play failed, and alarm will be crashed.
Todo: delete unhandled rejection when support atomic process.

alarm: add unhandled rejection as workaround

---

runtime/lib/component/turen.js
test/component/turen/events.test.js

Related: https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18578

turen: handle speech error 6 as network error

---

apps/cloudappclient/app.js
apps/cloudappclient/playerManager.js
apps/cloudappclient/service.js
test/apps/cloudAppClient/playerManager.test.js

save playerManager's debug info to property.

cloudappclient: support debug for playerManager

---

apps/cloudappclient/skill.js
test/apps/cloudAppClient/directive-sort.test.js

Fix sorting login error caused by statement `0 || 100`.

fixed(cloudappclient): fixed the login error of sort

---

packages/@yoda/bluetooth/a2dp-statemap.js
packages/@yoda/bluetooth/a2dp.js

In old bluetooth state mapping design, one current inflow state matches one outflow event. 
But for some case such as "broadcast ON/OFF", it may trigger redundant events. 
In order to  report the broadcast ON/OFF event accurately, we should add a new field to match the last inflow state.

bluetooth: add `lastInflow` field in state mapping

---

runtime/lib/component/app-scheduler.js
test/component/app-scheduler/process-management.test.js
test/fixture/crash-on-startup-app/app.js
test/fixture/crash-on-startup-app/package.json

Fixes an issue that app could not be created again if app exits on startup.

app-scheduler: status of apps exited on startup should be exited

---

runtime/lib/component/keyboard.js
test/component/keyboard/descriptor.test.js

Issues addressed in the PR:
- Missing keyup event while pressed multiple keys concurrently
- Not correct longpress time delta while pressing multiple keys concurrently
Fixes:
- https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19009

keyboard: fix conditions on composing multiple keys

---

runtime/lib/component/light.js
test/component/light/tts-sound.test.js
test/testsets.txt

Speaking effect should be stopped only while there is no tts contexts left.
Fixes:
- https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18351

light: naïve counter wrap for ttsSound speaking effect

---

apps/alarm/app.js
apps/alarm/package.json

1. When device was wakeup, stop actived alarm or reminder.
2. Alarm will be destroyed when device was sleep, other alarms and reminders can not play. on-boot notification will tell alarm to init again.

add media pause event & add on-boot notification

---

runtime/lib/component/keyboard.js
runtime/lib/descriptor/keyboard-descriptor.js
test/component/keyboard/prevent-defaults.test.js
test/descriptor/keyboard/event.test.js
test/descriptor/keyboard/fixture/ext-app/app.js
test/descriptor/keyboard/fixture/ext-app/package.json
test/testsets.txt

Apps may have showed interests on same key event. One `preventDefaults` call should not override another one app since the one been overridden doesn't have to handle such conditions.
Fixes:
- https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19020

keyboard: multiple apps have interests on same key event

---

apps/cloudappclient/app.js

On the release version, the test team can only use the property tool to implement the test. So keep the property and Flora debugging methods.

cloudappclient: support debug with property

---

runtime/lib/component/ota.js
test/component/ota/index.test.js
test/component/ota/mock.js

Fixes: https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19071

ota: do not delegate turenDidWakeUp is lifetime is been monopolized

---

apps/bluetooth/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19054
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18875
Because for the two scenes of Bluetooth phone & Bluetooth music, there is a setting of keepAlive=true to prevent it from being killed by system. After this setting, it will not receive onDestroy but only onBackground. And in lifecycle onBackground we check if current skill is bluetooth phone or bluetooth music, then disconnect the connection (This is according product definition).
However, after speak TTS such as `已连接上你的xxx`, we will call setBackground manually to let bluetooth goto background like a service. Therefore, during a call process, if bluetooth is opened and the relevant TTS is spoken. Then, after the bluetooth connection …

bluetooth: only set background in bluetooth skill after speak TTS

---

packages/@yoda/httpdns/src/httpdns.cc
packages/@yoda/multimedia/src/MediaPlayer.cc
packages/@yoda/tts/src/TtsNative.cc

This fixes an occasionally bug that causes the media crash on
`uv__finish_close`.
The crash log is:
```
#0  0x0000007fa50535ec in uv__finish_close (handle=0x478228)
at /home/ximin.chen/workspace-me/openwrt/build_dir/target-aarch64-linux-gnu/shadow-node/deps/libtuv/src/unix/core.c:248
#1  uv__run_closing_handles (loop=0x7fa510c100 <default_loop_struct>)
at /home/ximin.chen/workspace-me/openwrt/build_dir/target-aarch64-linux-gnu/shadow-node/deps/libtuv/src/unix/core.c:265
#2  uv_run (loop=0x7fa510c100 <default_loop_struct>, mode=mode@entry=UV_RUN_ONCE)
at /home/ximin.chen/workspace-me/openwrt/build_dir/target-aarch64-linux-gnu/shadow-node/deps/libtuv/src/unix/core.c:335
#3  0x0000007fa4fe97c4 in iotjs_start (env=0x7fa510b458 <current_env>)
at …
```

multimedia: free js handle at uv_close callback

---

packages/@yoda/multimedia/src/WavPlayer.cc

TYPE URL:https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19070
MODULE:jsruntime
SIDE EFFECT: NULL
Change-Id: I3544f9fcf2a2bb980164305c3bfab0725509167c

TYPE:BF:ID:NULL:TITLE:wavplayer.cc maybe block loss

---

runtime/services/lightd/service.js
test/services/lightd/loadfile.test.js
test/services/lightd/service-basic.test.js

Fixed:
1. Priority judgment error when user space and system space exist at the same time

fixed(lightd): fix the error in priority judgment

---

runtime/lib/descriptor/keyboard-descriptor.js
test/descriptor/keyboard/event.test.js

* Add `restoreAll` for easy restore all registered key codes and events.
* Throw error when input event name is unexcepted.

keyboard-descriptor: add restore all function and check unexpected event

---

etc/yoda/component-config.json
runtime/lib/app-runtime.js
runtime/lib/component/custom-config.js
runtime/lib/component/dbus-registry.js
runtime/lib/component/turen.js
runtime/lib/component/wormhole.js
runtime/lib/descriptor/activity-test-descriptor.js
test/apps/guidance/guidance-test.js
test/apps/ota/ota.test.js
test/apps/system/system-app-activity-api.test.js
test/apps/timer/timer-test.js
test/component/custodian/state-shift.test.js
test/runtime/voice-command.test.js

Continuous dialog should only be activated after end of voice context.

custom-config: activate continuous dialog only on end of voice context

---

apps/bluetooth/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19147
This fix is similar to #507.

bluetooth: do not need set background when received status mqtt

---

runtime/services/lightd/effects.js
runtime/services/lightd/service.js

Change-Id: I1288ff5616097fbbb731685136215a2d9625523a
When any light effect was stopped by lightd, and the option `keepLastFrame` is false, then the last color of last frame should be set to [0,0,0]

[lightd] fix lightd did not save the light color when the light effect was cleared.

---

apps/alarm/alarm-core.js
apps/alarm/app.js

update 'getNetworkState' to 'getWifiState'.
When the net is broken,  'getNetworkState' will be blocked, then alarm will be killed because alarm has no response for several minutes.  However, 'getWifiState' is not a blocked function.

update 'getNetworkState' to 'getWifiState'

---

apps/cloudappclient/app.js

open pickup in cloudappclient after cut skill exit for continuous dialogue.

cloudappclient: continuous dialogue only for cloudappclient

---

apps/alarm/alarm-core.js
apps/alarm/app.js
apps/alarm/node-cron.js

In prev change, I update getNetworkState to getWifiState, but getWifiState's result is not accurate, when u pull the cable, net is block, but getWifiState return connected. In changes, if first media play error, local media will be played.
When alarm and reminder have same time, reminder should start, alarm will not play.

handle alarm media play error & logic error that reminder and alarm have same time

---

packages/@yoda/wifi/index.js

Named connections are exclusive so that no more than one listener could be created.

@yoda/wifi: use anonymous connection

---

packages/@yoda/flora/index.js
packages/@yoda/flora/src/cli-native.cc

add options: 'beepInterval', 'norespTimeout'
flora tcp connection need keepalive(ping/pong)
deps:
https://github.com/yodaos-project/flora/pull/13

add options of Agent

---

runtime/services/ttsd/flora.js
runtime/services/ttsd/service.js
test/services/ttsd/pause-on-awaken.test.js

The cancel event was emitted when the new request coming rather than on reset.

ttsd: cancel event should be emitted on reset awaken

---

packages/@yoda/multimedia/src/MediaPlayer.cc
packages/@yoda/multimedia/src/MediaPlayer.h
test/stress/@yoda/multimedia/mediaplayer-multi-instance.js

Fixes an issue that caused by non-thread-safe function calls of `uv_async_init`.

multimedia: thread safe call from async threads

---

packages/@yoda/input/src/InputNative.cc
packages/@yoda/input/src/InputNative.h

Fixes an issue that caused by non-thread-safe function calls of `uv_async_init`.

input: thread safe call from async threads

---

packages/@yoda/tts/src/TtsNative.cc
packages/@yoda/tts/src/TtsNative.h

Fixes an issue that caused by non-thread-safe function calls of `uv_async_init`.

tts: thread safe call from async threads

---

apps/cloudappclient/app.js
apps/cloudappclient/manager.js
apps/cloudappclient/skill.js

should execute directives then exit when the value of NLP.TYPE is EXIT.

Feat/cloudappclient: execute directives then exit

---

packages/@yodaos/ttskit/convergence.js
runtime/services/ttsd/service.js
test/services/ttsd/index.test.js
test/services/ttsd/mock.js

Fixes an issue caused by async `cancel` emission

tts: asynchronous event callback

---

apps/battery/constant.json
test/apps/cloudAppClient/manager-eventRequest.test.js

All requests are directed to the same server, otherwise errors will occur after network reconnected.

use cloudapigw.open.rokid.com replace apigwrest.open.rokid.com

---

runtime/client/translator-in-process.js
test/activity/light-app.test.js
test/fixture/simple-app/app.js

Fixes an issue exposed by #599 to light app.

light-app: duplicate subscription on event

---

apps/custom-config/wakeup-effect.js

Change-Id: I09cc02ae5e94d4ab10ffcf8ece18c99d89cce1bc
There are 2 kinds of wakeup sound effect config data:
```
{
"wakeup": {"action": "open", "type": "0"," wakeupSoundEffects": []}
}
```
```
{
"wakeupSoundEffect": {"action": "open"}
}
```
for compatibility, we should set the field `type` to default value `"0"` if it is invalid.

custom-config: set wakeup sound effect config data with default type

---

apps/cloudappclient/app.js
apps/cloudappclient/manager.js
runtime/lib/descriptor/multimedia-descriptor.js
test/apps/cloudAppClient/manager-exit.test.js

This issue container the following change:
- fix requestOnce
- MEDIA.FINISH event add progress and duration in

feat: fix requestOnce and add progress info

---

apps/cloudappclient/service.js
apps/cloudappclient/skill.js

use playerManager replace directives

Fixed/cloudappclient: use playerManager replace directives

---

packages/@yodaos/application/audio-focus.js
packages/@yodaos/application/index.js
runtime/component/audio-focus.js
runtime/descriptor/audio-focus.js
test/@yodaos/application/audio-focus.test.js
test/component/audio-focus/index.test.js

An example usage:
```js
var focus = new AudioFocus(AudioFocus.Type.TRANSIENT)
focus.resumeOnGain = false
focus.onGain = () => {
focus.resumeOnGain = false
var player = focus.player
if (player == null) {
player = focus.player = new MediaPlayer()
}
if (focus.resumeOnGain) {
player.resume()
} else {
player.start('/opt/media/music.ogg')
}
}
focus.onLoss = (transient, mayDuck) => {
var player = focus.player
if (transient) {
player.pause()
focus.resumeOnGain = true
} else {
player.stop()
}
}
focus.request()
```

audio-focus: experimental client

---

package.json
packages/@yodaos/application/application.js
runtime/app-runtime.js
runtime/component/dbus-registry.js
runtime/component/dispatcher.js
test/@yodaos/application/application.test.js

```js
var Application = require('@yodaos/application').Application
module.exports = Application({
url: function url (urlObj) {
this.openUrl(urlObj.href)
}
})
```

@yodaos/application: delegate methods

---

apps/alarm/alarm-core.js
test/apps/alarm/alarm-core.test.js
test/testsets-local.txt
test/testsets.txt

alarm:[BF]reminder do not speak tts when timeout

---

etc/yoda/app-loader-config.json
runtime/app-runtime.js
runtime/component/app-scheduler.js
runtime/component/audio-focus.js
runtime/component/keyboard.js
runtime/component/lifetime.js
runtime/component/light.js
runtime/descriptor/keyboard.js
test/component/app-scheduler/light-app-management.test.js
test/component/app-scheduler/process-management.test.js
test/component/audio-focus/app-did-exit.test.js
test/component/keyboard/app-did-exit.test.js
test/component/keyboard/prevent-defaults.test.js
test/component/lifetime/bootstrap.js
test/descriptor/keyboard/event.test.js

Ease implementation of new components/descriptors interests on app did exit events.

runtime: delegates app did exit events to components/descriptors

---

packages/@yodaos/application/CMakeLists.txt
packages/@yodaos/application/vui/index.js
packages/@yodaos/application/vui/sequential-flow.js
test/@yodaos/application/vui/sequential-flow.test.js
test/testsets-local.txt

Example usage:
```js
var SequentialFlow = require('@yodaos/appliction/vui').SequentialFlow
var sf = new SequentialFlow([
/* Automatically handles SpeechSynthesisUtterance resolution/cancellation */
() => synth.speak('Playback down'), 
/* Automatically handles MediaPlayer resolution/cancellation */
() => new MediaPlayer().start('/data/media/music.mp3'),
(done, onCancel) => {
var customPlayer = new SomePlayer()
.on('end', () => done())
onCancel(() => player.stop())
}
])
sf.start() // Acquires audio focus
sf.on('end', () => {
// done
})
```

vui: Sequential Flow

---

packages/@yodaos/application/vui/app-task.js
packages/@yodaos/application/vui/atomic-task.js
packages/@yodaos/application/vui/index.js

* It means if any sub task is interrupted, the whole atomic task is interrupted.
* All sub tasks will be executed by sequence of original pass to constructor.
* An atomic task example which include 4 quark tasks: first speak a text, then play a piece of ringtone and then noop for a while and play ringtone again at last:
```js
var AtomicTask = require('@yodaos/application').vui.AtomicTask
var MediaPlayer = require('@yoda/multimedia').MediaPlayer
var tts = require('@yodaos/speech-synthesis').speechSynthesis
var mp = null
function playRingtone (cb, step, url) {
logger.debug(`step ${step}: play ringtone`)
mp = new MediaPlayer()
mp.on('playbackcomplete', cb)
mp.on('error', cb)
mp.start(url)
return (onInterruptedCallabck) => {
logger.debug(`step ${step} interrupted.`)
mp.stop() …
```

atomic-task: add atomic task utility

---

apps/bluetooth/app.js

Fix bug: https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=20454

bluetooth: reset lastIntent to prevent repeated speak music info

---

runtime/app/ext-app.js
runtime/client/ext-helper.js

Expected to be re-enabled on https://github.com/yodaos-project/ShadowNode/issues/517 got fixed

anr: temporary disable timer.unref

---

tools/apt-get-install-deps.sh

This fixes occasional installation issues on travis CI.

build, linux: exit 1 when something went wrong

---

packages/@yodaos/voice-interface/CMakeLists.txt
packages/@yodaos/voice-interface/index.js
packages/@yodaos/voice-interface/package.json

Example Usage:
```js
var voiceInterface = require('@yodaos/voice-interface').voiceInterface
var AudioFocus = require('@yodaos/application').AudioFocus
voiceInterface.on('oppress', () => {
// annonce availability
})
var focus= new AudioFocus()
focus.onGain = () => {
voiceInterface.startMonologue()
}
request.onLoss = () => {
voiceInterface.stopMonologue()
}
focus.request()
```

@yodaos/voice-interface: proposing voice interface API

---

runtime/app/ext-app.js

- rklog would redirect process log to logd if stdout is not a tty.
- `syslog` would set log prefix to process title
Also this would disable stdout redirection. Which means `console.log` would be disabled.
Usage example:
```sh
> logread -e /opt/apps/network
iotjs yoda-app /opt/apps/network[14805]: [INFO]    05-10 14:48:54.902542 [example-tag]☘ hello world
```
Ref: 
- https://openai-corp.rokid.com/gitweb?p=kamino_rokidos/open-platform/embedded-linux/rklog.git;a=blob;f=src/lib/RKLog.cpp;h=a8c9f19dbb30a6ad211e2b7e3326a0d6147bb02f;hb=0a43d4235fa990a495d85d41a7d66dba7a896400#l309
- https://linux.die.net/man/3/syslog

ext-app: force log redirection to logd

---

apps/bluetooth-music/app.js
apps/bluetooth/app.js
apps/bluetooth/bluetooth-service.js

1. fix onAudioFocusLost logic in transient.
1. add service start name.
2. correct runtime api.activity.exit.

bluetooth: fix bt music quit logic

---

runtime/lib/app-runtime.js

This moves `setMicMute()` behind the check for welcoming, it fixes the problem on delegating `runtimeDidLogin`.

runtime: setMicMute should be outside of welcome checking

---

runtime/lib/app-runtime.js
runtime/lib/component/lifetime.js
runtime/lib/descriptor/activity-descriptor.js
test/component/lifetime/monopolization.test.js

This adds an option `filterCut` to `startMonologue` to let application specify if allowing the cut apps when in monopolized.

lifetime: add option `allowCut` to disable cut app when monopolized.

---

packages/@yodaos/application/audio-focus.js
runtime/component/audio-focus.js
test/@yodaos/application/audio-focus.test.js
test/component/audio-focus/index.test.js

- add test coverage on focus instance recycling.

audio-focus: should not re-grant identical focus duplicated requesting

---

apps/bluetooth/app.js
apps/cloudappclient/app.js
apps/playercontrol/app.js
apps/system/app.js
apps/system/package.json
runtime/lib/app-runtime.js

Switch the playback status of scene applications.
usage: Configure the buttons that need to be triggered or any others can trigger this method.
@param {string} [playerControlURL] - The URL of playerControl. playerControl app will be requested when there is no scene app to resume.
example: edit `/etc/yoda/keyboard.json`
```json
click": {
"debounce": 1000,
"runtimeMethod": "playerControl",
"params": ["yoda-skill://playercontrol/resume"]
}
```

runtime: support playerControl api

---

runtime/services/vuid/watchdog.js

This writes the current watchdog file descriptor to the `watchdog.fd`, then debugger could listen the watchdog feeding via:
```shell
$ WATCHDOG_FD=`getprop watchdog.fd`
$ strace -p <vui-daemon pid> | grep "write(${WATCHDOG_FD}"
```

vuid: set watchdog fd for better listen

---

benchmark/multimedia/mediaplayer.js

Result:
takes 0 232.715208 millisecs

multimedia: add benchmark on start player

---

benchmark/boot.sh

Currently a booting process takes around 15 seconds.
shutdown: 2s
adb available: 15s
system available: 1s

benchmark: add tool to evaluate boot time

---

apps/cloudappclient/app.js
apps/cloudappclient/manager.js
apps/cloudappclient/skill.js
test/apps/cloudAppClient/manager-exit.test.js
test/apps/cloudAppClient/skill.test.js

changes:
1. requestOnce should not interrupt others skill
2. requestOnce should continue execution

Fixed/cloudappclient: requestOnce should not interrupt others skill

---

runtime/component/audio-focus.js
runtime/descriptor/audio-focus.js
test/component/audio-focus/broadcast.test.js

Expose audio focus shifting broadcast to apps so that apps like launcher could automatically close wake-up engine on `TRANSIENT_EXCLUSIVE` focus got granted.
Related: https://github.com/yodaos-project/yoda-book/pull/8

audio-focus: broadcast focus shifts

---

packages/@yodaos/application/service.js
test/@yodaos/application/service.test.js

Expose application instance getter from service instance.

service: add getApplication instance method

---

packages/@yodaos/speech-synthesis/index.js
packages/@yodaos/speech-synthesis/src/pcm-player.cc
packages/@yodaos/speech-synthesis/src/pcm-player.h
packages/@yodaos/speech-synthesis/src/speech-synthesizer.cc
test/@yodaos/speech-synthesis/index.test.js
test/@yodaos/speech-synthesis/src/voice-interface.cc

Notable Changes:
- enforced pair start/terminal event (start/end, start/cancel).
- cancel while speechSynthesizer pending.

speech-synthesis: immediate cancellation

---

apps/cloud-player/test/voice/tts-stream.test.js
apps/cloud-player/voice/tts-stream.js
packages/@yodaos/application/audio-focus.js
packages/@yodaos/mm/mock.js

Fixes flora target not exists error on url `yoda-app://cloud-player/play-tts-stream`
Related: #751 hoisted speech-synthesis event `start` to player started (previously on first data written to pulseaudio).
- Added `gained` and `lost` event to TestSuite.AudioFocus

cloud-player: defer removing GetStreamChannel to focus lost

---

docs/ota.md
runtime/services/otad/delegation.js
runtime/services/otad/index.js
test/services/otad/delegation.test.js

To enable more customizable operation on download complete, the PR add a new delegation `notify`

ota: delegate notification on done

---

runtime/services/ttsd/service.js
test/services/ttsd/index.test.js

fixed/ttsd: should not emit event after emit termination event

---

etc/yoda/memory-sentinel.json
runtime/app/app-bridge.js
runtime/app/default-launcher.js
runtime/component/app-scheduler.js
runtime/component/memory-sentinel.js
test/component/memory-sentinel/high-water-mark.test.js
test/component/memory-sentinel/index.test.js
test/component/memory-sentinel/low-free-memory.test.js

Previously on YodaOSv7, we would rely on the voluntarily exit of apps to recollect the memory pages. Yet this strategy does do buggy things to app codes and works poorly on memory managements, we'd propose a new solution to reduce the redundant apps quits and make the memory usage more efficient.
In the PR, we introduced two strategy of memory management:
1. App memory water mark: apps should not consume memory more than the predefined water mark. Though the key and visible app that taking the burden of user interface(media player/views), which can inevitably increase the memory usage, could have a higher high water mark of memory.
2. Free available memory warnings: whilst the regular memory checks on single apps could limit a single app memory usage, a group of apps accumulates memory …

memory-sentinel: kill app on low memory available

---

runtime/client/translator-ipc.js
runtime/component/broadcast.js
runtime/component/flora.js
test/component/broadcast/index.test.js

Make broadcast signature simplified to:
app#broadcast(channel: string, extra: any)
Also makes broadcast signature unified across different channels with
arbitrary extras.

broadcast: simplify broadcast signature

---

runtime/component/app-scheduler.js
runtime/component/chronos.js
runtime/component/flora.js
test/component/app-scheduler/anr.test.js

ANR currently works with timestamps on alive report. While Date.now()
would jump forward(or backward) on time synced, alive report timestamp
delta calculation would not be accurate thus should be reset on time
change.

app-scheduler: reset ANR after time changed by ntpd

---

packages/@yodaos/application/application.js
runtime/app-runtime.js
runtime/component/flora.js
test/@yodaos/application/application.test.js
test/@yodaos/application/class-loader.test.js

To keep Fauna protocol clean and language agnostic, we’d revisit JS related
API and refactor these API. This PR is part of the process. Though we’d keep
actual API untouched to keep API stability at this time, an additional
url parse would be performed at client side.

runtime: pass url event argument as url string

---

apps/alarm/media-manager.js

[MDF]stop alarm/reminder ringtone when wakeup

---

runtime/component/flora.js
test/component/flora/open-url.test.js

Fixes issue introduced by #787

runtime: query not merged on opening url with format

---

packages/@yodaos/application/audio-focus.js
test/@yodaos/application/audio-focus.test.js

Example Usage:
```js
var focus = new AudioFocus()
focus.onGain = () => {
assert(focus.state === AudioFocus.State.ACTIVE)
}
focus.request()
```

audio-focus: focus state getter

---

apps/cloud-player/test/voice/player.test.js
apps/cloud-player/voice/player.js
packages/@yoda/multimedia/mediaplayer.js

Notable Changes:
- Added `AudioFocus#state` readonly property to indicate audio focus states. (depends on #799)
- `MediaPlayer#start` no longer recursively call self on `prepared` to prevent unexpected testing behavior.

test: cloud-player pause/resume

---

runtime/component/app-scheduler.js
runtime/component/dbus-registry.js
test/component/app-scheduler/anr.test.js
test/component/app-scheduler/app-management.test.js
test/component/broadcast/index.test.js

App killed by ANR would result in SIGKILL. Previously we use signal
to determine if app was killed intentionally. Yet in this case the
daemon app does be killed intentionally still required to be restarted
to prevent unexpected results.
This PR removed this check and restart daemonized app unconditionally. 
For previously use case of no-restart-kill, either app should be de-
daemonized or runtime should be disabled.

scheduler: restart daemon app unconditionally

---

apps/alarm/media-manager.js

[BF][21802]abandon audiofocus when alarm finish

---

runtime/services/otad/wget.js

ota: set wget default timeout to 15 seconds

---

packages/@yoda/multimedia/mediaplayer.js
test/@yoda/multimedia/compat.test.js
test/@yoda/multimedia/mediaplayer-chaos.test.js
test/@yoda/multimedia/mediaplayer.test.js

Prevent unexpected error `MediaPlayerWrap has not been set up`.

multimedia: delayed start should be suppressed on stop

---

runtime/services/otad/step.js
test/services/otad/step.test.js

ota: make image size fetching optional by inferring from ota info

---

apps/cloud-player/voice/tts-stream.js

Prevent confusing stream name between consecutive stream request.

cloud-player: un-declare get stream channel immediately

---

apps/alarm/alarm-core.js
apps/alarm/node-cron.js

[BF][22023]can not ring when alarm/reminder set same time

---

packages/@yodaos/speech-synthesis/src/pcm-player.cc
packages/@yodaos/speech-synthesis/src/pcm-player.h

While player has fired pending event `end` yet JS callback not being
called, a `cancel` operation has been invoked by JS thread there would
be two termination event `end` and `cancel` in respectively order.
Termination events should only been fired once and exclusively.

speech-synthesis: race condition on end and cancelling

---

packages/@yoda/util/_.js
packages/@yodaos/application/index.js
packages/@yodaos/application/now-playing-center.js
runtime/component/media-controller.js
runtime/descriptor/media-controller.js
test/@yoda/util/_.test.js
test/@yodaos/application/now-playing-center.test.js
test/component/media-controller/index.test.js
test/testsets.txt

Use cases:
- I have a media player app, and I want to use the media keys on my keys on device to control it.
- I have a media player app and I want to use the headset controls on my headphones to control it.
- I have a media player app and I want to use the mobile soft keys (e.g. as done on iOS and Android lock screens) to control it.
Usage: 
```js
var NowPlayingCenter = require('@yodaos/application').NowPlayingCenter
var nowPlayingCenter = NowPlayingCenter.default
// event `command` would only be fired after now playing info has been set.
nowPlayingCenter.on('command', command => {
switch (command.type) {
case NowPlayingCenter.CommandType.TOGGLE_PAUSE_PLAY: 
// toggle pause play
case NowPlayingCenter.CommandType.PLAY: 
// set playing
case NowPlayingCenter.CommandType.PAUSE:
// set paused …
```

media-controller: media controller support

---

apps/cloud-player/README.md
apps/cloud-player/constant.js
apps/cloud-player/voice/player.js
apps/cloud-player/voice/tts-stream.js

Also add `pause` event broadcasting.

cloud-player: implement remote command support

---

apps/system/README.md
apps/system/app.js
apps/system/package.json
apps/system/reply.json
apps/system/test/index.test.js

This patch reads the battery feature, and just reply a guiding TTS for the `/shutdown` and `/reboot` ops, and also adds the the `@yoda/system` docs.

system: add replies for shutdown/reboot if no battery at manifest

---

packages/@yodaos/application/now-playing-center.js
test/@yodaos/application/now-playing-center.test.js

now-playing-center: should not emit duplicated event "command"

---

runtime/component/audio-focus.js
test/@yodaos/application/audio-focus.test.js
test/component/audio-focus/index.test.js

Focuses lost as transient would not be removed from registry.

audio-focus: transient request should not loss as transient

---

packages/@yoda/multimedia/src/media-player.h
packages/@yodaos/speech-synthesis/src/speech-synthesizer.h
test/@yoda/multimedia/mediaplayer.test.js
test/@yodaos/speech-synthesis/index.test.js

Cpp exceptions that were enabled by default would abort the process, yet we would like the errors been handled in JS land (and maybe unfortunately handled by uncaughtException listeners or exiting the process with non-zero exit code).

speech-synthesis: disable n-api cpp exceptions

---

apps/cloud-player/test/voice/player.test.js
apps/cloud-player/voice/player.js

Set player to null to prevent unexpected MediaPlayer not setup error
on the case of player operations on sequent speech-synthesis/multimedia
event.

cloud-player: unset player on focus loss

---

cmake/packages.cmake

Currently versions of dependencies declared in `cmake/packages.cmake` are not locked properly through repo manifest. This might cause future compatibility issues if any dependency updates at master branch and losses backward compatibility.

deps: lock YodaGitPackages version

---

packages/@yodaos/application/vui/atomic-task.js

fix bug [22419](https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=22419): [必现][系统]播放音乐时，语音“计时10s”，计时结束后，音乐不会恢复播放

atomic-task: audio focus type should be transient

---

.travis.yml
cmake/packages.cmake

Though these packages still should be built on CI for testing.
Related: https://openai-corp.rokid.com/#/c/17689/
Related: https://openai-corp.rokid.com/#/c/17695/

packages: remove yoda-git-packages on building images

---

client/c/CMakeLists.txt

Fixes: https://github.com/yodaos-project/yodart/issues/854

build: make yodaosclient_c depends on yodart-api-c

---

package.json
packages/@yodaos/speech-synthesis/src/speech-synthesizer.cc
tools/apt-get-install-deps.sh

build: use clang-format nom package

---

runtime/services/lightd/index.js

`sounder.init` holds the connection to pulseaudio, and it would keep
writing empty buffers to alsa.

lightd: do not init prepared audio if `player.lightd.holdcon` is 0

---

runtime/app/app-bridge.js
runtime/app/default-launcher.js
runtime/app/executable-launcher.js
runtime/component/app-scheduler.js

Generate coredump on application not responding for convenient debugging.

app-scheduler: generate coredump on ANR

---

test/testsets.txt

The `httpdns` module is not used, and it's related with the Rokid's cloud protocol.

test: disable the httpdns tests

---

runtime/lib/component/turen.js
test/component/turen/reset-awaken.test.js

Flora could not accept a null as its arguments.

turen: fix the invalid flora args on recoverPausedOnAwaken()
