modules/volume/index.js
runtime/lib/runtime.js

When the volume is less than 5, the wakeup would is versed on volumes.

volume, runtime: fix the mute/unmute when volume is less than 5

---

runtime/lib/runtime.js

just let ro test execute completely

comment two lines in lifecycle

---

modules/context/index.js
modules/context/plugins/EventHandler.js
runtime/lib/runtime.js

init: when system is loaded
online: network and system is online
offline: network disconnected

plugin: add more events for init/online/offline

---

.gitignore
modules/bluetooth/binding.gyp
modules/bluetooth/index.js
modules/bluetooth/src/BluetoothWrap.cc
modules/bluetooth/src/BluetoothWrap.h
modules/logger/index.js

蓝牙：接入 librokid-bt 库

---

modules/dbus/lib/dbus.js
modules/vui/lib/app.js
runtime/lib/runtime.js

support homebase

---

runtime/lib/apis/login.js

runtime: use v2 login api

---

packages/@yoda/input/index.js
packages/@yoda/input/src/InputNative.cc
runtime/lib/component/keyboard.js
test/runtime/keyboard/descriptor.test.js

keyboard: slide event implementation

---

apps/bluetooth/app.js

This commit will bring side effect when cross with cloud apps.
See detail in https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&t=html&id=16910

bluetooth:revert dd21748667d60196108acc1a9a18139f82ebfb71

---

runtime/lib/app/executable-proc.js
runtime/lib/app/ext-app.js
runtime/lib/component/app-loader.js
runtime/lib/component/app-scheduler.js

Added manifest field:
- `manifest.rawExecutable` *boolean*

scheduler: executable proc implementation

---

runtime/lib/cloudapi/index.js

cloud-api: update basic info with cloud checked data

---

tools/runtime-install

tools: options to not install configuration files

---

runtime/lib/component/dbus-registry.js

dbus-registry: add api `OpenUrl`

---

apps/system/app.js
runtime/lib/app-runtime.js
runtime/lib/app/activity-descriptor.js
test/runtime/app-runtime/voice-command.test.js
test/runtime/light-app.test.js
types/yoda-rt.d.ts

Related:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=16229

runtime: hibernate device on sleep command

---

README.md
codecov.yml

meta: add badges for ci and codecov

---

packages/@yoda/bluetooth/player.js

bluetooth: Fix flora msg data reference error.

---

runtime/lib/component/flora.js

forgot remove old code about Caps
Change-Id: I72d32c49e3d8ccb2ce301571c5f62c500e0c3fae

fix js runtime error of getNlpResult

---

packages/@yoda/ota/index.js

ota: should unlock proc lock whether error occurs or not

---

runtime/lib/component/dbus-registry.js
runtime/lib/component/flora.js

mock: upgrade flora asr2nlp to new flora API

---

runtime/lib/component/app-loader.js

loader: should suppress error on batch loading

---

etc/app-loader-config.json
runtime/lib/app-runtime.js
runtime/lib/component/app-loader.js
runtime/lib/component/dbus-registry.js
runtime/services/vuid/index.js
tools/runtime-install

control-api: reload apps on-demand

---

CMakeLists.txt
apps/cloudappclient/app.js
etc/app-loader-config.json
packages/@yoda/flora/index.js
packages/@yoda/flora/src/cli-native.cc
packages/@yoda/flora/src/cli-native.h
packages/@yoda/system/src/SystemNative.cc
runtime/lib/app-runtime.js
runtime/lib/component/app-loader.js
runtime/lib/component/dbus-registry.js
runtime/lib/component/flora.js
runtime/services/vuid/index.js
tools/runtime-install

v7.29.4 Release Proposal

---

packages/logger/binding.cc
test/logger/simple.test.js

May cause error if log content has "%s".
Change-Id: Idfed0b82d2d5a6d7456ded8d25501f8138e19da6

logger: fix incorrect use of jslog function.

---

runtime/lib/component/dbus-registry.js

control-api: list packages by app id

---

packages/@yoda/ota/index.js

ota: should unlock proc lock whether error occurs or not (#83)

---

packages/@yoda/flora/src/cli-native.cc

Agent may receive incorrect additional REQUEST msg,
because pending msgs queue not erase REQUEST msg immediately.
Change-Id: I0ec0fac2f079a1c5730fcfa7ebb7197c0d80b975

fix bug of flora-cli.node

---

packages/@yoda/ota/index.js
test/@yoda/ota/read-info.test.js

ota: error tolerance on malformed info.json

---

runtime/lib/component/dbus-registry.js

control-api: nlp intent command

---

packages/@yoda/flora/comp.js
packages/@yoda/flora/index.js
packages/@yoda/flora/src/cli-native.cc
test/@yoda/flora/flora.test.js

add param 'options' for Agent constructor and Agent.subscribe
Change-Id: Iec1d9aee2b2e212151548eedff224f63264da314

flora: modify flora node api

---

packages/@yoda/system/index.js

system: add get unified device name function.

---

runtime/lib/component/wormhole.js

wormhole: add event dispatcher to handle mobile/cloud api commands

---

apps/custom-config/app.js
runtime/lib/app-runtime.js

…e app to false, and call activity.exit() to exit app after all the work has been done
Change-Id: I95a7cda5fe7542b0b3118db8b0f8d7c3b8172819

fix vt words setting broke the scene app

---

LICENSE.md
apps/alarm/alarm-core.js
apps/alarm/expression.js
apps/alarm/node-cron.js
apps/custom-config/app.js
packages/@yoda/flora/comp.js
packages/@yoda/flora/index.js
packages/@yoda/flora/src/cli-native.cc
packages/@yoda/ota/index.js
packages/@yoda/system/index.js
packages/logger/binding.cc
runtime/lib/app-runtime.js
runtime/lib/component/dbus-registry.js
runtime/lib/component/wormhole.js
test/@yoda/flora/flora.test.js
test/@yoda/ota/read-info.test.js
test/logger/simple.test.js

v7.29.6 Release Proposal

---

packages/@yoda/flora/src/cli-native.cc
packages/@yoda/flora/src/cli-native.h
packages/@yoda/flora/stress/flora-stress.js

add param of flora subscribe callback
add param 'name'
Change-Id: Idc78745b23f89396545e215119f11e0b374e87cd

modify param of flora subscribe msg callback

---

runtime/lib/app/ext-app.js

ext-app: descriptor method return value error tolerance

---

apps/cloudappclient/skill.js

fixed(cloudappclient): Fix task calculation error

---

apps/custom-config/app.js
res/light/setSysStandby.js

Change-Id: Ic77595b456cf6b10c93387802c526957e619a549

standby light: add standby light support

---

packages/@yoda/bluetooth/a2dp-statemap.js

bluetooth: fix state mapping table typo.

---

packages/@yoda/bluetooth/a2dp.js

bluetooth: add state unhit log and optimize state log display.

---

runtime/services/ttsd/index.js

close #157 
Change-Id: I11c82c76c5959c96886b76a1d386d29c638e2d12

tts: set declaimer with persist prop `rokid.tts.declaimer`

---

packages/@yoda/bluetooth/a2dp.js

bluetooth: fix lint error.

---

runtime/lib/app-runtime.js
runtime/lib/component/app-loader.js
test/runtime/app-loader/loader.test.js

dbus-app: fix missing dbus interface fields

---

apps/ota/app.js
apps/ota/strings.json

ota: refactoring with strings.json

---

runtime/lib/component/turen.js

turen: replace bluetooth related functions with new a2dp interface.

---

apps/alarm/alarm-core.js
apps/alarm/app.js
apps/alarm/data-migration.js

since alarm may crash while first binding account, this pr is a fix for this issue

v7.29.7 Release Fix Proposal 

---

packages/@yoda/bluetooth/a2dp.js

bluetooth: fix while play prev/next song, forget unmute issue.

---

tools/test

test: support multi devices

---

apps/volume/app.js
etc/keyboard.json

volume: decrease volume with fast mute

---

apps/alarm/package.json
apps/battery/package.json
apps/bluetooth/app.js
apps/bluetooth/package.json
apps/cloudappclient/package.json
apps/composition-de-voix/package.json
apps/custom-config/package.json
apps/guidance/package.json
apps/log-switch/package.json
apps/network/package.json
apps/ota/package.json
apps/system/package.json
apps/timer/package.json
apps/volume/package.json

manifest: update internal apps format

---

README.md

Correct the badge links of codecov service.

meta: correct the codecov badge links

---

packages/@yoda/tts/index.js
packages/@yoda/tts/src/TtsNative.cc
packages/@yoda/tts/src/TtsNative.h
packages/@yoda/tts/src/TtsService.cc
packages/@yoda/tts/src/TtsService.h
runtime/services/activation/activation.cc
runtime/services/activation/activation.h
runtime/services/lightd/effects.js
runtime/services/ttsd/index.js

Change-Id: I7bec14f77c644bf3df7d7fbae7a253ab5469e63d

controlling long links of wavplayers or opusplayer by setting prop

---

runtime/lib/component/dnd-mode.js
test/runtime/dnd-mode/dnd-mode.test.js
test/testsets.txt

fix dnd mode time checking error, fix dnd mode test

dnd-mode: Fix dnd mode time checking error

---

packages/@yoda/flora/comp.js
packages/@yoda/flora/index.js
packages/@yoda/flora/src/cli-native.cc
packages/@yoda/flora/src/cli-native.h
runtime/services/ttsd/flora.js
test/@yoda/flora/flora.test.js

change 'get' to 'call'
add declareMethod, removeMethod
Change-Id: I6d44138090d51ac6e329c7f9848ff5e6aad1dfc4
depend on PR https://github.com/Rokid/yoda-flora/pull/3

flora: add rpc call

---

etc/component-config.json
runtime/lib/app-runtime.js

Customize component load paths.

runtime: component load paths

---

runtime/lib/component/wormhole.js

wormhole: the component should be on this.runtime

---

runtime/lib/component/dispatcher.js

dispatcher: fix this reference

---

packages/@yoda/bolero/loader.js
runtime/lib/component/app-loader.js
test/@yoda/bolero/loader/index.test.js
test/runtime/app-loader/loader.test.js

loader: skip load paths if doesn’t exist

---

test/runtime/lifetime/context-options.test.js

test: not created app on lifetime test case

---

runtime/lib/component/dispatcher.js
runtime/lib/component/ota.js
test/runtime/dispatcher/index.test.js

dispatcher: failed dispatching on no component responses

---

runtime/lib/descriptor/httpgw-descriptor.js

activity: fixes accessing error on namespace httpgw

---

runtime/lib/component/light.js
runtime/services/lightd/flora.js
runtime/services/lightd/index.js

`setGlobalAlphaFactor` changed to `flora-post-persist` from `dbus-method`

dnd-mode: global alpha factor for service[lightd] should be persistent.

---

test/@yoda/flora/flora.test.js

add test case for flora remote method call

add test cases for flora

---

packages/@yoda/cloudgw/index.js
runtime/lib/descriptor/httpgw-descriptor.js

httpgw: options to set request timeout

---

packages/@yoda/battery/index.js
packages/@yoda/flora/disposable.js
runtime/lib/component/battery.js
runtime/lib/component/flora.js
test/helper/mock.js
test/runtime/battery/index.test.js
test/testsets.txt

battery: query battery info

---

runtime/lib/component/flora.js

battery: pick first of flora message array as message

---

etc/component-config.json
packages/@yoda/flora/CMakeLists.txt
runtime/lib/component/battery.js
test/runtime/battery/index.test.js

flora: install all js files under package root

---

runtime/lib/component/battery.js
test/runtime/battery/index.test.js

battery: determine if battery is supported by field `batSupported`

---

tools/helper/flora-emitter.js

tools: upgrade flora-emitter to new flora API

---

runtime/lib/component/battery.js
runtime/lib/component/wormhole.js

battery: handle query battery info by wormhole

---

apps/custom-config/wakeup-effect.js
runtime/lib/component/custom-config.js

Change-Id: I6c2f8df941636b7d3c169ce2eca70ce69eff6e20
When then custom-wakeup-effects-path is not exits, there ware some problems to download file.

custom-config: fix custom-wakeup-effects path check

---

packages/@yoda/system/index.js
packages/@yoda/system/src/SystemNative.cc
runtime/lib/app-runtime.js
runtime/lib/component/battery.js

runtime: add shutdown method

---

runtime/lib/component/battery.js
runtime/lib/component/turen.js
test/runtime/battery/index.test.js

turen, battery: wakeup interception of battery

---

apps/battery/app.js
apps/battery/constant.json
apps/battery/light/battery.js

fix json file require error, prop key flag remove persist

---

runtime/lib/component/battery.js
test/runtime/battery/index.test.js

battery: close pick up with turen

---

apps/battery/light/battery.js

battery-app: fix battery acconnect media error

---

runtime/lib/descriptor/httpgw-descriptor.js
test/fixture/ext-app/app.js
test/runtime/descriptor/httpgw.test.js
test/testsets.txt

httpgw: onGetProp dont return promise

---

apps/alarm/alarm-core.js
apps/alarm/app.js
apps/alarm/node-cron.js
apps/alarm/pattern-validation.js

Fix alarm bugs :
1. Update arithmetic when combine reminder's tts. 
2. One request update config file only once.

Alarm fix same reminder tts play not smoothly bug

---

runtime/lib/component/lifetime.js

lifetime: do not emit preemption if appId is falsy

---

runtime/lib/app-runtime.js

runtime: delegate runtimeDidInit

---

runtime/lib/component/keyboard.js

keyboard: delegate keyboardWillRespond

---

apps/volume/app.js

volume: more friendly volume adjusting strategy

---

runtime/services/activation/activation.cc

Change-Id: Ie51cd4e8dcb6ab2074d5171ca83665ce6f6ea22d
Remove cjson head file.

activatiopn: remove cjson head file

---

runtime/lib/component/keyboard.js

keyboard: arguments should not be available inside arrow fn

---

apps/cloudappclient/app.js

The media will automatically pause when waking up, so can remove the pause operation.

fixed: remove unnecessary pauses action

---

apps/volume/app.js

volume: correct count to help

---

apps/custom-config/continuous-dialog.js
apps/custom-config/standby-light.js

Change-Id: I105a9b228a524379f68a8d100281e89459cabcbd
If the costom-config changed by intent, we should call the cloud api to save it.

custom-config: save the custom-config changes by intent

---

runtime/lib/app-runtime.js

runtime: notification apps filter option

---

runtime/lib/component/app-loader.js

app-loader: notification channel registration

---

runtime/lib/component/app-loader.js
test/runtime/app-loader/api.test.js

loader: fix cleared notification channels on reload

---

runtime/lib/component/wormhole.js

wormhole: proactively set MQTT online

---

runtime/lib/app-runtime.js
runtime/lib/app/ext-app.js
runtime/lib/component/app-scheduler.js
runtime/lib/component/turen.js
runtime/lib/descriptor/activity-descriptor.js
runtime/lib/descriptor/turen-descriptor.js

turen: add support for toggling switch on turen wake up engine

---

runtime/lib/component/app-loader.js
runtime/lib/component/dbus-registry.js
test/fixture/malformed-apps/unknown-notification/package.json
test/runtime/app-loader/malformed-app.test.js

loader: unexpected error on reload for apps with unknown notifications

---

apps/cloudappclient/app.js
apps/cloudappclient/manager.js
apps/cloudappclient/package.json

gsensor feature support for cloudappclient

frature: add gsensor support in cloudapp

---

apps/ota/app.js
apps/ota/strings.json
packages/@yoda/ota/condition.js
packages/@yoda/ota/index.js
runtime/lib/component/ota.js
test/@yoda/ota/condition.test.js

Announce why OTA is unavailable.

ota: unavailability announcement

---

packages/@yoda/bluetooth/hfp-statemap.js
packages/@yoda/bluetooth/hfp.js
packages/@yoda/bluetooth/index.js
packages/@yoda/bluetooth/protocol.json

1. Add bluetooth hands-free profile.
2. Add hands-free interface in bluetooth module enterance.

bluetooth: add bluetooth phony framework.

---

apps/cloudappclient/app.js
apps/cloudappclient/package.json

This reverts commit bfda414749cb7a274289595cd8898c3c89e16365.

Revert "gsensor shake feature support for cloudappclient (#306)"

---

apps/ota/app.js
packages/@yoda/ota/index.js
runtime/lib/component/ota.js
runtime/services/otad/index.js
test/runtime/ota/index.test.js
test/runtime/ota/mock.js
test/testsets.txt

test: ota component delegations

---

apps/cloudappclient/app.js
apps/cloudappclient/package.json

code format and support gsensor-shake

---

tools/README.md
tools/runtime-install
tools/switch-env

convenience tool to switch device env

tool: convenience tool to switch device env

---

runtime/lib/component/app-scheduler.js

scheduler: re-use futures on app creation

---

runtime/lib/app-runtime.js

bootstrap: bring tts service connection forward and announcing welcome audio

---

apps/system/app.js
runtime/lib/app-runtime.js
runtime/lib/component/dbus-registry.js
runtime/lib/descriptor/activity-descriptor.js

Add `runtime.hibernate` to prevent runtime to login.

runtime: hibernation & idling

---

runtime/lib/app-runtime.js

runtime: options to welcome on runtime wake up

---

packages/@yoda/multimedia/mediaplayer.js
packages/@yoda/multimedia/src/MediaPlayer.cc
runtime/lib/descriptor/multimedia-descriptor.js
runtime/services/multimediad/index.js
runtime/services/multimediad/service.js

Don't merge: awaiting native lib to be ready.

mediaplayer: eqMode accessor

---

apps/bluetooth/app.js
apps/bluetooth/config.json
apps/bluetooth/http-util.js
apps/bluetooth/resources.json
apps/bluetooth/strings.json

1. Add song to cloud favorites.
2. Add player controller.
3. Change `answer`/`reject` call from `confirm` mode to `NLP` mode.
4. User new `getXxxxState()` to solve complex product definitions.
5. Remove `hfp.open()` due to it has been binded with `a2dp.open()`.

bluetooth: regular update application code.

---

apps/cloudappclient/directive.js
test.js
test/apps/cloudAppClient/directive.test.js

This supports the property `nowait` for directives, and refine the directive lines.

cloudappclient: support `nowait` property for directives

---

runtime/lib/app-runtime.js
runtime/lib/component/battery.js

runtime: ignore battery events on hibernation

---

runtime/lib/app-runtime.js
runtime/lib/component/dbus-registry.js

runtime: suppress network event on welcoming

---

packages/@yoda/bolero/loader.js
runtime/lib/component/dbus-registry.js

A convenience method to inspect runtime components status.

runtime: component inspector

---

packages/@yoda/util/_.js
runtime/lib/component/turen.js
test/runtime/turen/events.test.js

Closes https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18240

turen: speech error been suppressed in progress of asr

---

runtime/lib/descriptor/activity-descriptor.js

activity: declare background event

---

apps/cloudappclient/app.js
apps/cloudappclient/eventRequestApi.js
apps/cloudappclient/eventRequestMap.json
apps/cloudappclient/manager.js
packages/@yodaos/mediakit/convergence.js
runtime/lib/component/dbus-registry.js
runtime/lib/descriptor/multimedia-descriptor.js
runtime/services/multimediad/index.js
runtime/services/multimediad/service.js
test/runtime/services/multimediad/final.test.js
test/runtime/services/multimediad/service.test.js

fixed(cloudappclient): upload pause/resume event to cloud

---

apps/bluetooth/app.js

bluetooth: change addToFavorite() from callback to promise

---

apps/bluetooth/app.js

Note: This commit is related with PR#344.

bluetooth: fix music still playing after app already in background

---

packages/@yoda/audio/index.js
test/@yoda/audio/simple.test.js
tools/test

tool: test should exit with non-zero code on pipe fail

---

packages/@yoda/ota/condition.js
packages/logger/index.js
runtime/lib/component/keyboard.js
test/@yoda/ota/condition.test.js
test/@yoda/ota/get-available-info.test.js
test/runtime/keyboard/prevent-defaults.test.js
tools/test

test: keyboard delegation made key event handling asynchronous

---

test/logger/simple.test.js
test/testsets.txt

logger: fix test case crash while testing simple and multiple args

---

apps/composition-de-voix/app.js
runtime/lib/component/lifetime.js
test/runtime/lifetime/carrier.test.js

Rokid app has released a version that had not tested over YODAOS.
Fixes https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18477

lifetime: carrier should be re-activated on borne app set background

---

apps/ota/app.js
packages/@yoda/ota/index.js

Fixes https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18428

ota: announce downloading progress on user query

---

packages/@yoda/util/_.js
test/@yoda/util/_.test.js

util: no appending format

---

runtime/lib/descriptor/activity-descriptor.js

activity: add setContextSkillId

---

apps/bluetooth/app.js

bluetooth: sync local volume to remote bluetooth device

---

apps/timer/RKDownTimer.js

timer: add trace and speech card

---

packages/@yoda/flora/comp.js
runtime/lib/component/skill-host.js
tools/helper/flora-invoker.js

skill-host: declare skill options query interface

---

packages/@yodaos/ttskit/convergence.js

ttskit: store tts playing state for convenient querying

---

runtime/lib/component/lifetime.js
test/runtime/lifetime/context-options.test.js

lifetime: kept alive scene app shall not enter background on cut preemption

---

runtime/lib/app-runtime.js

runtime: turn off mic-mute light effect on silencing

---

apps/ota/app.js

ota: download progress rounding

---

packages/@yoda/system/src/SystemNative.cc

system: reboot doesn’t support param charging

---

apps/cloudappclient/app.js
apps/cloudappclient/service.js
apps/cloudappclient/skill.js
runtime/services/multimediad/index.js

cloudappclient: add skill options

---

runtime/services/multimediad/index.js

cloudapiclient: should convert the playerId to string

---

runtime/lib/descriptor/multimedia-descriptor.js
runtime/services/multimediad/index.js

mediaplayer: the arguments of options is option

---

apps/cloudappclient/service.js

cloudappclient: pos should be corrected to progress

---

apps/cloudappclient/service.js

cloudappclient: correct the turn of media/voice

---

runtime/services/multimediad/index.js

fixed: remove unnecessary json.stringify

---

runtime/lib/component/lifetime.js
test/runtime/lifetime/context-options.test.js

Resolves https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18588

lifetime: kept alive app should be put to background on deactivating

---

apps/playercontrol/app.js

playercontrol: use openurl to resume app 

---

packages/@yoda/util/index.js
packages/@yoda/util/math.js
test/@yoda/util/math.test.js

1. random(): temporary replace standard Math.random() due to it has unresolved issue, see https://github.com/Rokid/ShadowNode/issues/331
2. randInt()
3. randBool()

util: add math utility functions

---

runtime/lib/descriptor/activity-descriptor.js

api: add getContextSkillId

---

runtime/lib/component/keyboard.js
test/component/keyboard/descriptor.test.js

Resolves https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18618

keyboard: long press with interrupting keydown-keyup of another key code

---

runtime/lib/app-runtime.js

Change-Id: I130e82bff2bb9de65d84761e0f5ac30e16117bd3
Add no-tts option for the light effect `setMute`. When scene app is active, no tts played.

add no-tts option for mute light effect.

---

apps/system/app.js

Resolves https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18088

system: friendly informing on app not installed

---

apps/bluetooth/strings.json

bluetooth: modify TTS text to avoid let user confused.

---

include/async_invoke.h

fix compile error of wrong parameter type

---

packages/@yoda/flora/index.js
packages/@yoda/flora/src/cli-native.cc

content of flora msg can push undefined value

---

packages/@yoda/util/index.js
packages/@yoda/util/time.js
test/@yoda/util/time.test.js

util: add time utility functions

---

runtime/lib/app-runtime.js
runtime/lib/component/flora.js
runtime/lib/descriptor/tts-descriptor.js
runtime/services/ttsd/flora.js
runtime/services/ttsd/service.js
test/descriptor/tts.test.js
test/fixture/ext-app/app.js

ttsd: duplicated emission of tts events

---

runtime/lib/descriptor/tts-descriptor.js
test/descriptor/tts/event.test.js
test/descriptor/tts/fixture/ext-app/app.js
test/descriptor/tts/fixture/ext-app/package.json
test/descriptor/tts/tts.test.js
test/testsets.txt

Fixes an issue that apps could not receive TTS events from VUI.

test: tts descriptor events

---

apps/bluetooth/app.js

* correct logic of flip event.
* cancel mute while fliped according new PRD.

bluetooth: handle cross of bt-music/bt-call/flip-event

---

apps/bluetooth/app.js

bluetooth: suppress disconnected prompt while not explicit intent

---

CMakeLists.txt
apps/volume/app.js
packages/@yodaos/application/CMakeLists.txt
packages/@yodaos/application/context-manager.js
packages/@yodaos/application/package.json
test/@yodaos/application/context-manager.test.js
test/testsets.txt

For convenience context management, `@yodaos/application` provides a simple context wrapper to manage multiple context been processed concurrently.
Resolves https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18256

@yodaos/application: in app process state storage

---

apps/bluetooth/app.js
apps/bluetooth/strings.json

bluetooth: handle bluetooth_info intent

---

apps/volume/app.js

Fixes https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18690

volume: add_volume_num/dec_volume_num volume number normalization

---

test/runtime/services/lightd/loadfile.test.js

Change-Id: I474e5cc6f301ed4289ded7502bf5b1d44c67ca22
fix: can not exit normally when `lighd.service.loadfile` error.

test: fix test exiting error

---

apps/bluetooth/app.js

bluetooth: move play-control from entrance to exit

---

packages/@yoda/bluetooth/a2dp-statemap.js
packages/@yoda/bluetooth/a2dp.js

bluetooth: add 'mode' to identify a2dp-sink special play state

---

docs/flora-messages.md

flora: add docs/flora-messages.md

---

runtime/lib/component/flora.js

invoke flora remote method speech-service.asr2nlp
deps:
https://github.com/Rokid/yoda-speech-service/pull/3

flora: reimplement getNlpResult

---

packages/@yoda/trace/index.js
packages/logger/index.js

@yoda/trace: suppress trace uploading error

---

runtime/lib/component/lifetime.js
runtime/lib/component/turen.js
test/component/lifetime/index.test.js
test/component/turen/events.test.js

Resolves:
- https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18739
- https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18291

turen: speech error 8 should deactivate app memorized on voice coming

---

runtime/lib/component/wormhole.js

Resolves https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18656

wormhole: send response to app on reset_settings

---

runtime/lib/component/turen.js
test/component/turen/events.test.js
test/component/turen/finalization.test.js
test/component/turen/helper.js

Resolves:
- https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18798

turen: suppress interactive events while mic muted

---

runtime/lib/component/turen.js
test/component/turen/pick-up.test.js

Fixes:
- https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18739

turen: manually pick up should not close cut app on speech error 8

---

runtime/lib/app-runtime.js

init announcements might last a foreseeable long duration. This PR introduced naïve breaks in `runtime.init`.
Fixes:
- https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18628

runtime: break-able init announcements

---

runtime/lib/component/turen.js
test/component/turen/events.test.js
test/component/turen/lifetime.test.js
test/helper/mock.js

Fixes https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18788

turen: no recovering reset awaken doesn’t resume scene app

---

runtime/lib/app-runtime.js
runtime/lib/component/dbus-registry.js
runtime/lib/component/flora.js
runtime/lib/component/skill-host.js
runtime/lib/component/wormhole.js

skill-host: upload skill options on ASR to NLP

---

apps/timer/app.js

timer: clear skill context after exit

---

runtime/lib/component/light.js
runtime/services/lightd/flora.js

Change-Id: Iee21bd2d1c6d55c81486affee60fe4d09f415062
Awake and pickup light effects are status, so they should be resumed.

light: awake.js and setPickup.js option `shouldResume` should be true

---

apps/custom-config/wakeup-effect.js

Change-Id: Iae2d562bdc18bc02b5ef8271ed5b1f0a546b7b43
add config check.

custom-config: check the custom wakeup effect config.

---

apps/timed-sleep/app.js

timed-sleep: correct activity.exit() opportunity

---

runtime/lib/component/turen.js
test/component/turen/events.test.js

Fixes https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18862

turen: voice coming should clear no voice input timer

---

runtime/lib/component/dbus-registry.js
runtime/lib/component/turen.js
test/component/turen/events.test.js

turen: timeout constants should not be modified

---

apps/bluetooth/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18871

bluetooth: catch error while playing ringtone to avoid crash

---

apps/timer/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18871

timer: fix timer lifecycle issue and optimize flow code

---

apps/volume/app.js

Related https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18820

volume: announce fast volume adjust guide on exactly third time

---

apps/bluetooth/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18774
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18874

bluetooth: reset intent history after intent has been handled

---

runtime/lib/component/skill-host.js

flora get rokid.skills.state info from cloudappclient ,timeout time is 100ms,its too short,the default time is 200ms

Delete timeout param, use default param in speech

---

apps/ota/app.js
packages/@yoda/system/index.js
runtime/lib/app-runtime.js
runtime/lib/component/battery.js
test/@yoda/system/system.test.js
test/component/battery/getter.test.js
test/component/battery/helper.js
test/component/battery/index.test.js
tools/helper/flora-invoker.js
tools/helper/upgrade.js

While device powered off unexpectedly, we would like to know why it powered off after reboot.
Related: https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18812

battery: store power off reason for easy debugging

---

runtime/lib/component/wormhole.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18927

component: set app event mock voice command preemptive as false

---

apps/bluetooth/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18711

bluetooth: add timeout for play bluetooth music

---

runtime/lib/component/lifetime.js
test/component/lifetime/context-options.test.js

Fixes https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18923

lifetime: emit eviction with form in context options

---

runtime/lib/component/custodian.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18606
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18835

component: add wifi connection timeout

---

apps/timer/app.js

timer: catch error while operating media to avoid crash

---

apps/bluetooth/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18974
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18981

bluetooth: handle call case while disconnected from phone

---

apps/bluetooth/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18760

bluetooth: only speak but not set backstage when play music intent

---

apps/bluetooth/app.js
apps/custom-config/standby-light.js

set the bluetooth call zIndex to: 2. Because setSystemStandby.js to be the lowest.

fixed the zIndex of bluetooth call

---

apps/timed-sleep/app.js

timed-sleep: reset keep alive flag to protect lifecycle

---

apps/timer/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19040

timer: reset keep alive flag to protect lifecycle

---

apps/composition-de-voix/app.js
runtime/lib/component/lifetime.js
test/component/lifetime/carrier.test.js

Fixes an issue of mixed multiple context in fast resolving.
Fixes: 
- https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=18750
- https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19024

comp-de-voix: strict fast resolving

---

apps/timer/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19060

timer: handle double click to stop ringtone

---

apps/bluetooth/app.js
packages/@yoda/bluetooth/hfp.js

Fix bug: two ringtone played when incoming a call.
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19019

bluetooth: only play incoming ringtone if necessary

---

apps/bluetooth/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19062

bluetooth: play alternative sound for TTS error when weak connection

---

packages/@yoda/httpsession/index.js

httpsession: optimize the description to clear these functions

---

apps/timer/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19075

timer: shut up when goto background and optimize code

---

apps/alarm/app.js
apps/alarm/package.json
runtime/lib/app-runtime.js
runtime/lib/component/app-loader.js

Add system notification `on-system-booted` which notifies apps on system reboot and woken up.

runtime: add system notification `on-system-booted`

---

apps/bluetooth/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19026

bluetooth: do not need set background when received app event

---

apps/cloudappclient/app.js

Fixed(cloudappclient): should call next() after a directive was complete

---

apps/bluetooth/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19059

bluetooth: check if get song info failed

---

packages/@yoda/tts/src/TtsNative.cc
packages/@yoda/tts/src/TtsNative.h

fix: compile error due to #511

---

packages/@yodaos/mediakit/convergence.js

fixed(mediaKit): url must bind with playerid in mediaclient

---

runtime/lib/app/light-app.js
runtime/lib/component/app-scheduler.js
test/component/app-scheduler/light-app-management.test.js

light-app: app should be exited if crashes on startup

---

apps/network/app.js

Fixes: 
- https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19110

network: play standby light on beginning of setup

---

apps/bluetooth/strings.json

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19173

bluetooth: revise TTS words according PRD

---

apps/cloudappclient/eventRequestApi.js
test/apps/cloudAppClient/manager-eventRequest.test.js

replace https with httpsession for optimize CPU performance.

fixed(cloudappclient): use httpsession

---

apps/cloudappclient/app.js

Change-Id: I63487f97436f06e1b3d3bba5050880ec5b923715
The error from activity.media.resume should be caught.

cloudappclient: the error from activity.media.resume should be caught.

---

apps/timer/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19185

timer: handle timer_comback intent

---

apps/custom-config/wakeup-effect.js

Change-Id: I6340f17d852b37b3ce0c13305c28b605cf11d58d
Remove check for wakeup effect.

custom-config: remove wakeup effect check

---

apps/custom-config/vt-word.js
runtime/lib/component/turen.js
runtime/lib/descriptor/turen-descriptor.js

Change-Id: Iebb6845afc1cd50d77760e0986dde852c398eaa1
Refactor vt words interface.

custom-config: refactor vt word interface

---

apps/alarm/alarm-core.js
apps/alarm/app.js
apps/alarm/node-cron.js
apps/cloudappclient/app.js
apps/cloudappclient/manager.js
apps/cloudappclient/skill.js
apps/custom-config/vt-word.js
apps/custom-config/wakeup-effect.js
apps/timer/app.js
runtime/lib/component/turen.js
runtime/lib/descriptor/turen-descriptor.js

* [5cad4e1e] - **custom-config**: remove wakeup effect check (#557) (FeelyChau)
[57a631c4] - handle alarm media play error & logic error that reminder and alarm have same time (#555) (ynliSonia)
* [daaaca55] - **cloudappclient**: Fix an issue that cannot be played from the beginning (#556) (sudo)
* [ac11af70] - **cloudappclient**: upload speedchange event after prepared event (#549) (sudo)
* [adc14f00] - **cloudappclient**: continuous dialogue only for cloudappclient (#552) (sudo)
* [446d466b] - **timer**: handle timer_comback intent (#553) (Morrowind Xie)
[803ea8aa] - the error from activity.media.resume should be caught. (#548) (FeelyChau)

release: v7.33.6 proposal

---

apps/timer/app.js
apps/timer/config.json

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19111

timer: set pickup mode when only ask for countdown without time intent

---

runtime/lib/cloudapi/mqtt/client.js

mqtt: forward the cmcc message if topic not found

---

packages/@yoda/exodus/index.js

@yoda/exodus: migrate ota info

---

test/@yoda/flora/flora.test.js

should wait a while for flora sub/decl finish

fix bug for js flora unit test

---

runtime/lib/component/dnd-mode.js

Change-Id: I4cf6aabf220c1a9ef1b35d86876e141f8d0eb6cb
`dt.getDay()` -> `dt.getDate()`

dnd-mode: fix date format for log

---

packages/@yoda/oh-my-little-pony/index.js

on-my-little-pony: start cpu profiler on SIGUSR1

---

apps/bluetooth/app.js
apps/bluetooth/strings.json
packages/@yoda/bluetooth/a2dp-statemap.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19186

bluetooth: add connect failed device name in TTS

---

runtime/lib/component/app-scheduler.js
test/component/app-scheduler/process-management.test.js

app-scheduler: create app right after app destructed

---

packages/@yoda/bluetooth/a2dp.js
packages/@yoda/bluetooth/hfp.js

bluetooth: set interface return value as boolean for test purpose

---

packages/@yoda/httpsession/index.js
packages/@yoda/httpsession/src/httpsession.cc
test/@yoda/httpsession/request.test.js

This fixes the blocking problem which caused by initializing the handle at the module `Init` function.

httpsession: move static async handle into task to manager

---

packages/@yoda/bluetooth/index.js

bluetooth: modify bluetooth adapter for unit test

---

test/@yoda/bluetooth/a2dp-sink-test.js
test/@yoda/bluetooth/a2dp-source-test.js
test/@yoda/bluetooth/bluetooth.test.js
test/@yoda/bluetooth/hfp-test.js
test/apps/cloudAppClient/manager-eventRequest.test.js
test/testsets.txt

* fix cloutAppClient unit test failed
* add A2DP-SINK unit test
* open
* play
* pause
* stop
* syncVol
* mute
* unmute
* prev
* next
* query
* close
* add A2DP-SOURCE unit test
* open
* connect
* disconnect
* discovery
* close
* add HFP unit test
* open
* answer
* hangup
* dial
* close

bluetooth: add bluetooth interface unit test

---

apps/bluetooth/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&id=19394

bluetooth: handle bluetooth music playing during call

---

apps/composition-de-voix/app.js

comp-de-voix: should exit if there is no directives available

---

packages/@yoda/flora/stress/flora-stress.js

update flora js stress test

---

packages/@yoda/multimedia/src/MediaPlayer.cc

fixed/multimedia: delete listener object

---

apps/bluetooth/app.js

Fix bug:
https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=19196

bluetooth: change `setAppType` as synchronized promise function

---

packages/@yoda/input/src/InputNative.cc
packages/@yoda/input/src/InputNative.h

input: fix segv on disconnect before properly started

---

packages/@yoda/flora/src/cli-native.cc
tools/helper/flora-emitter.js
tools/helper/flora-invoker.js
tools/helper/flora-listener.js

Add node.js compatibility support

flora: support node.js

---

runtime/services/ttsd/flora.js
test/services/ttsd/flora.test.js
test/services/ttsd/mock.js

ttsd: tts not recovered if paused by voice coming multiple times

---

packages/@yodaos/application/context-manager.js
test/@yodaos/application/context-manager.test.js

@yodaos/application: pass through activity.exit arguments

---

apps/network/app.js

Change-Id: I10ce369ce380b8e3188c54ac642c294c660231e7
Add the function `getSn` for BLE protocol.
#591

add function getSn for ble protocol

---

packages/@yoda/cloudgw/index.js
test/@yoda/cloudgw/cloudgw.test.js

httpgw: migrate to httpsession

---

runtime/lib/component/wormhole.js

Change-Id: Ie4ac53156b6d61a6556324e1c5a49a8c6f52b2b3
Add mqtt msg to shell args.

wormhole: Add mqtt msg to shell args

---

packages/@yoda/oh-my-little-pony/health-reporter.js
packages/@yoda/oh-my-little-pony/index.js
runtime/services/healthz/healthz
runtime/services/lightd/index.js
runtime/services/multimediad/index.js
runtime/services/ttsd/index.js
runtime/services/vuid/index.js

Health Reports and checks on services.

oh-my-little-pony: health check

---

packages/@yoda/oh-my-little-pony/CMakeLists.txt

oh-my-little-pony: install script

---

apps/alarm/alarm-core.js

alarm: fix prototype function scope not correct on playMediaPrepared

---

packages/@yoda/flora/src/cli-native.cc
packages/@yoda/flora/src/cli-native.h
tools/clang-format

fix abort: napi FunctionReference may release not at main thread

---

.travis.yml
apps/alarm/alarm-core.js
packages/@yoda/flora/src/cli-native.cc
packages/@yoda/flora/src/cli-native.h
packages/@yoda/oh-my-little-pony/CMakeLists.txt
packages/@yoda/oh-my-little-pony/health-reporter.js
packages/@yoda/oh-my-little-pony/index.js
runtime/client/translator-in-process.js
runtime/lib/component/wormhole.js
runtime/services/healthz/healthz
runtime/services/lightd/index.js
runtime/services/multimediad/index.js
runtime/services/ttsd/index.js
runtime/services/vuid/index.js
test/activity/light-app.test.js
test/fixture/simple-app/app.js
tools/apt-get-install-deps.sh
tools/brew-install-deps.sh
tools/clang-format
tools/memory-viewer

* [de0529cd] - **fix abort**: napi FunctionReference may release not at main thread (#607) (mingzc0508)
* [b44953f9] - **alarm**: fix prototype function scope not correct on playMediaPrepared (#612) (lanyuqingri)
* [1806676b] - **oh-my-little-pony**: install script (#613) (legendecas)
* [a46bacfb] - **build**: integrate travis to run lint (#608) (legendecas)
* [e1611641] - **oh-my-little-pony**: add health report and check (#604) (legendecas)
* [e2bf0644] - **light-app**: duplicate subscription on event (#605) (legendecas)
* [a8d4c27c] - **wormhole**: add mqtt msg to shell args (#600) (FeelyChau)
* [7823da4e] - **tools**: add memory detail in graph (#595) (qile222)

release: v7.33.7 proposal

---

tools/test

tools: run tests in presets by default

---

.travis.yml
package.json
packages/logger/index.js
runtime/lib/app-runtime.js
runtime/lib/component/app-loader.js
runtime/lib/component/custom-config.js
runtime/lib/component/dbus-registry.js
runtime/lib/component/dispatcher.js
runtime/lib/component/flora.js
runtime/lib/component/keyboard.js
runtime/lib/component/wormhole.js
runtime/lib/helper/config.js
runtime/services/lightd/flora.js
runtime/services/multimediad/flora.js
runtime/services/ttsd/flora.js
test/helper/index.js
test/testsets-local.txt
tools/apt-get-install-deps.sh
tools/brew-install-deps.sh
tools/install-shadow-node.sh
tools/test

ci: enable local test sets on ci

---

runtime/lib/descriptor/keyboard-descriptor.js
test/component/keyboard/prevent-defaults.test.js
test/descriptor/keyboard/fixture/ext-app/app.js

keyboard: delegates keydown/keyup events

---

apps/alarm/alarm-core.js
apps/alarm/app.js
apps/alarm/data-migration.js
apps/alarm/request.js
apps/cloudappclient/app.js
apps/cloudappclient/manager.js
apps/cloudappclient/service.js
apps/cloudappclient/skill.js
apps/custom-config/wakeup-effect.js
runtime/lib/descriptor/keyboard-descriptor.js
test/apps/cloudAppClient/manager-exit.test.js
test/component/keyboard/prevent-defaults.test.js
test/descriptor/keyboard/fixture/ext-app/app.js
tools/test

* [7ea1ba46] - **alarm**: data-migration not success on-system-boot,should retry when on-ready (#626) (lanyuqingri)
* [8072dc9b] - **cloudappclient**: use playerManager replace directives (#623) (sudo)
* [3ccc258e] - **keyboard**: delegates keydown/keyup events (#620) (legendecas)
* [bd9d54b7] - **cloudappclient**: fix requestOnce() and add progress info (#618) (sudo)
* [54590484] - **custom-config**: set wakeup sound effect config data with default type (#621) (FeelyChau)
* [e5338bac] - **tools**: run tests in presets by default (#617) (legendecas)

release: v7.33.8 proposal

---

runtime/component/audio-focus.js
runtime/descriptor/audio-focus.js
runtime/lib/descriptor.js
test/component/audio-focus/index.test.js
test/helper/mock.js
test/testsets-local.txt

audio-focus: basic implementation

---

apps/alarm/data-migration.js

v7.33.8 Fixup
* [90513560] - **alarm**: fix data-migration data format not correct when no alarm or no reminder (#638) (lanyuqingri)

release: v7.33.9 proposal

---

apps/alarm/alarm-core.js
test/apps/alarm/alarm-core.test.js

alarm:[BF]weekday/weekend alarm can not response when timeout

---

apps/bluetooth/app.js

bluetooth: fix the device name, it should in tel format

---

apps/cloudappclient/skill.js
test/apps/cloudAppClient/player-control.test.js
test/testsets-local.txt
test/testsets.txt

- add URL character escaping
- fix a variable error

Fixed/cloudappclient: add URL character escaping and fix a variable error

---

runtime/app-runtime.js
runtime/descriptor/runtime.js

runtime: add setPhase for setup app

---

apps/volume/app.js

volume-app: deref context on url of context manager

---

packages/@yodaos/application/audio-focus.js
runtime/component/audio-focus.js
test/component/audio-focus/index.test.js

audio-focus: tests on exclusive requests

---

.gitignore
package.json
packages/@yodaos/speech-synthesis/CMakeLists.txt
packages/@yodaos/speech-synthesis/index.js
packages/@yodaos/speech-synthesis/src/pcm-player.cc
packages/@yodaos/speech-synthesis/src/pcm-player.h
packages/@yodaos/speech-synthesis/src/speech-synthesizer.cc
packages/@yodaos/speech-synthesis/src/speech-synthesizer.h
packages/@yodaos/speech-synthesis/src/thr-pool.h
test/testsets-local.txt

Implements new Speech Synthesizer API.
Notable Changes:
- New speak requests do not cancel previously speaking requests automatically. Rather, queued according to Web SpeechSynthesis API Spec instead.

speech-synthesis: speech synthesizer

---

runtime/component/chronos.js
test/component/chronos/index.test.js

chronos: fix flaky case on pushing collision jobs

---

runtime/app/app-bridge.js
runtime/app/executable-proc.js
runtime/component/app-loader.js
runtime/component/app-scheduler.js
test/descriptor/bootstrap.js
test/descriptor/effect/index.test.js
test/testsets-local.txt

app-bridge: app metadata

---

apps/cloud-player/app.js
apps/cloud-player/package.json
packages/@yodaos/speech-synthesis/src/speech-synthesizer.cc
packages/@yodaos/speech-synthesis/src/speech-synthesizer.h
runtime/component/flora.js

cloud-player: generic cloud directives player

---

apps/cloud-player/app.js
packages/@yodaos/speech-synthesis/index.js

cloud-player: support transient/sequential directives

---

apps/volume/app.js
apps/volume/strings.json

volume-app: support YODAOS v8 API

---

packages/@yodaos/application/application.js
test/@yodaos/application/service.test.js

yodaos-application: get service

---

apps/cloudappclient/eventRequestApi.js
apps/cloudappclient/manager.js
packages/@yoda/util/index.js
packages/@yoda/util/retries.js
test/@yoda/util/retries.test.js

cloudappclient: request with maxRetry

---

packages/@yoda/network/index.js

- add two methods, resetDns() & removeAllOfWifi()

Feature/network: add two methods, resetDns() & removeAllOfWifi()

---

packages/@yodaos/application/service.js

service: delegate openUrl function

---

packages/@yodaos/application/vui/app-task.js
packages/@yodaos/application/vui/atomic-task.js

atomic-task: fix module.exports

---

packages/@yoda/util/fs.js
packages/@yodaos/storage/index.js
test/@yodaos/storage/index.test.js

yodaos-storage: local storage getter

---

runtime/client/ext-helper.js
runtime/client/ext-test-entry.js
runtime/component/app-scheduler.js

Support `yoda-cli am launch <app-name> --mode test`

app: test runner

---

runtime/services/lightd/flora.js

lightd: wake up effect applied by runtime phase

---

runtime/descriptor/runtime.js
test/descriptor/runtime/index.test.js
test/testsets-local.txt

descriptor: fix the setPhase and add test case

---

.dockerignore
.travis.yml
CMakeLists.txt
Dockerfile
cmake/module/FindNodeAddon.cmake
cmake/packages.cmake
cmake/yodart-api.cmake
cmake/yodart.cmake
packages/@yodaos/speech-synthesis/CMakeLists.txt
packages/logger/CMakeLists.txt
packages/logger/index.js
runtime/app-runtime.js
tools/build-yodart.sh
tools/rklogger/CMakeLists.txt

Notable Changes:
- Added cmake module `NodeAddon`: convenience macro to add a node addon target
- Added cmake macro `node_addon_find_package`: convenience macro add searches third-party libraries and import with cmake imported target
- Normalize cmake variables to respect existing or builtin cmake variables

build: node-addon

---

tools/rklogger/rklogger.c

Fix: log stalls when run command adb shell rklogger XXXX

---

apps/bluetooth/app.js
apps/cloudappclient/eventRequestApi.js
apps/cloudappclient/manager.js
packages/@yoda/util/index.js
packages/@yoda/util/retries.js
test/@yoda/util/retries.test.js
tools/apt-get-install-deps.sh
tools/rklogger/rklogger.c

* [d6c6f9d8] - **rklogger**: log stalls when run command adb shell rklogger (#695) (Zhu Yongjian)
* [a3b724cc] - **build, linux**: exit 1 when something went wrong (#699) (Yazhong Liu)
* [02de3719] - **bluetooth**: reset lastIntent to prevent repeated speak music info (#678) (Morrowind Xie)
* [3e1b5381] - **cloudappclient**: request with maxRetry (#664) (sudo)

release: v7.37.1 proposal

---

apps/system/app.js
runtime/app-runtime.js
runtime/component/audio-focus.js
runtime/component/dbus-registry.js
runtime/descriptor/runtime.js
runtime/descriptor/visibility.js
test/component/audio-focus/index.test.js

Expose visibility api to apps.

descriptor: visibility api for apps

---

packages/@yoda/flora/src/cli-native.cc
packages/@yoda/flora/src/cli-native.h

must delete napi reference in main thread

flora: fix abort() during flora call

---

apps/system/app.js

app/system: support play an alternative voice while speak TTS failed

---

apps/bluetooth-music/app.js
apps/bluetooth/app.js
apps/bluetooth/bluetooth-service.js
apps/bluetooth/config.json
apps/bluetooth/package.json
apps/bluetooth/resources.json
apps/bluetooth/strings.json

* Add call event handler.
* Speak different text on OPEN according previous design.
* Trim unused code in JSON.
* Remove Rokid related words.

bluetooth: add call event handler and remove unused code

---

cmake/yodart.cmake
etc/hotplug.d/ntp/post-ntpd-event
runtime/component/app-loader.js
runtime/component/broadcast.js
runtime/component/flora.js

Depends on https://openai-corp.rokid.com/#/c/15476/

ntp: broadcast yodaos.on-time-changed on ntp synced

---

cmake/packages.cmake

build: install packages with source permissions

---

packages/@yoda/bluetooth/a2dp.js

iPhone volume adjustment bar jumps while playing bluetooth music.

bluetooth: do not sync volume to phone while setting system volume by self

---

apps/custom-config/wakeup-effect.js

Change-Id: I2143d3042e4bed861e5c58abb90afacb9e224a60
fix: When the wakeup effect config from intent applied,  tts is not played.

[custom-config]fix bug: when the wakeup effect config from intent applied,  tts is not played.

---

tools/configure-network.bat
tools/runtime-install.bat
tools/runtime-op.bat
tools/upgrade.bat

Support below batch commands for Windows:
* configurate-network
* runtime-install
* runtime-op
* upgrade

tools: add yoda runtime tools for windows env

---

etc/yoda/keyboard.json

keyboard: fix bluetooth app URL

---

tools/runtime-install.bat

tools:remove wrong deletion commands

---

apps/bluetooth-music/app.js
apps/bluetooth/bluetooth-service.js

bluetooth: fix upload to clound interface

---

runtime/lib/cloudapi/mqtt/client.js

Change-Id: I7c4aa77d9a36b646045a74ec1e755ac307308349
Set default topic if topic is null, the default topic configures by user.

mqtt: set default topic if topic is null

---

packages/@yoda/property/index.js
packages/@yoda/property/src/PropertyNative.cc

@yoda/property: iterates over key-value pairs

---

runtime/lib/app-runtime.js

It tries to speed up the bootstrap.

runtime: move startDaemonApps() after `ready` event

---

runtime/component/chronos.js

Expect fixing https://github.com/yodaos-project/yodart/issues/718

chronos: duplicated execution of non-repeating job

---

packages/@yoda/battery/index.js
packages/@yoda/manifest/index.js

Related: https://github.com/yodaos-project/yodart/pull/688

battery: fast resolve if feature battery is not enabled

---

apps/bluetooth/app.js
apps/cloudappclient/app.js
apps/playercontrol/app.js
apps/system/app.js
apps/system/package.json
packages/@yoda/battery/index.js
packages/@yoda/bolero/loader.js
packages/@yoda/manifest/index.js
runtime/lib/app-runtime.js
runtime/lib/component/lifetime.js
runtime/lib/descriptor/activity-descriptor.js
runtime/services/vuid/watchdog.js
test/@yoda/bolero/loader/index.test.js
test/component/lifetime/monopolization.test.js

* [9cbc3ea9] - **battery**: fast resolve if feature battery is not enabled (#734) (legendecas)
* [94012c83] - **vuid**: set watchdog fd for better listen (#732) (Yazhong Liu)
* [a6ad76fd] - **runtime**: support playerControl api (#728) (sudo)
* [86bfbc87] - **loader**: overridable component (#218) (legendecas)
* [c6ce8baf] - **lifetime**: add option `allowCut` to disable cut app when monopolized. (#717) (Yazhong Liu)

release: v7.37.3 proposal

---

runtime/services/lightd/flora.js

awake: apply voice interface availability on awaken

---

apps/timed-sleep/app.js
packages/@yodaos/application/context-manager.js

timed-sleep: context manager

---

runtime/services/lightd/flora.js

lightd: apply voice interface availability on both voice_coming and local_awake

---

apps/cloud-player/app.js
apps/cloud-player/constant.js
apps/cloud-player/test/index.test.js
apps/cloud-player/voice/player.js
apps/cloud-player/voice/tts-stream.js
runtime/client/ext-helper.js

Add playback control url 
- `yoda-app://cloud-player/pause`, 
- `yoda-app://cloud-player/resume`, 
- `yoda-app://cloud-player/stop`.

cloud-player: add playback control support

---

packages/@yodaos/speech-synthesis/CMakeLists.txt
packages/@yodaos/speech-synthesis/index.js
packages/@yodaos/speech-synthesis/src/logger.h
packages/@yodaos/speech-synthesis/src/pcm-player.cc
packages/@yodaos/speech-synthesis/src/speech-synthesizer.cc

Also implements alternative log macros for host build.

speech-synthesis: apply rklog

---

package.json
test/README.md
tools/test

optimize the way to run unittest that can generate coverage data just in a file when run test-local

test: update test-local

---

apps/ota/app.js
packages/@yoda/ota/condition.js
packages/@yoda/ota/index.js
runtime/services/otad/README.md
runtime/services/otad/index.js
runtime/services/otad/step.js
test/services/otad/delegation.test.js

Examples (also test coverage) on raw shell command delegation of otad.

ota-deletation: test on raw shell command delegation

---

packages/@yodaos/speech-synthesis/index.js
test/@yodaos/speech-synthesis/index.test.js

speech-synthesis: speaking light effect should be resume-able

---

packages/@yoda/httpsession/index.js
packages/@yoda/httpsession/src/httpsession.cc

Add options.trust_all to buildRequest

httpsession: Add options.trust_all to buildRequest

---

runtime/app-runtime.js

This feature should be implemented in launcher app.

app-runtime: remove turen startup flag

---

runtime/lib/app-runtime.js

fixed/app-runtime: fix unbind syntax error

---

apps/alarm/alarm-core.js
test/apps/alarm/alarm-core.test.js

PR-URL: https://github.com/yodaos-project/yodart/pull/648
Reviewed-By: yorkie <yorkiefixer@gmail.com>
Reviewed-By: legendecas <legendecas@gmail.com>

[v7.28.x] alarm: weekday/weekend alarm can not response when timeout (#648)

---

README.md
packages/@yoda/wifi/index.js
packages/@yoda/wifi/src/binding.cc
test/@yoda/wifi/info.test.js

add `setApModeSync` and `setStationModeSync`

wifi switch mode sync support

---

runtime/client/ext-helper.js

Prevents app from unexpected promise unhandled rejection.

app-entry: suppress single failed alive report

---

packages/@yodaos/storage/index.js
test/@yodaos/storage/local-storage.test.js

Use `/data/AppData` instead of `/data/appData`.

local-storage: capitalize app data dir name

---

packages/@yoda/multimedia/src/MediaPlayer.cc
packages/@yoda/system/src/SystemNative.cc

Change-Id: Ifbf418d4ef0839d561a3e69d6b949dcdfc64cef3

system: add glibc config

---

packages/@yodaos/speech-synthesis/index.js

speech-synthesis: verbose logger on condition branches

---

runtime/component/flora.js
test/component/audio-focus/index.test.js
test/component/flora/bootstrap.js
test/component/flora/fauna-invoke.test.js
test/component/flora/fauna-status-report.test.js
test/component/flora/fauna-subscribe.test.js
test/component/flora/open-url.test.js

flora-component: stringify queries on opening url with format

---

packages/@yodaos/speech-synthesis/src/speech-synthesizer.cc
test/@yodaos/speech-synthesis/index.test.js
test/@yodaos/speech-synthesis/src/voice-interface.cc

speech-synthesis: emit error to JS on receiving error status

---

packages/@yoda/audio/index.js

audio: post persist message for each audio channel volume changes

---

apps/cloud-player/app.js
packages/@yodaos/application/application.js
test/@yodaos/application/application.test.js

Fixes compatibility issue introduced by #787

application: should parse url with query

---

packages/@yoda/oh-my-little-pony/index.js

Do no require additional condition property to enable these features.

oh-my-little-pony: enable signals to profile by default

---

runtime/component/flora.js

A workaround for glibc dns resolving issue.

runtime: force routing table reset on network reconnected

---

runtime/component/flora.js

runtime: ignore non-network-state message

---

apps/cloud-player/app.js
apps/cloud-player/test/app.test.js

cloud-player: splice voices on finishing

---

runtime/lib/app-runtime.js
test/runtime/init/index.test.js

runtime: fix skill stack error.

---

apps/bluetooth-music/app.js
apps/bluetooth/bluetooth-service.js
apps/bluetooth/package.json
packages/@yoda/bluetooth/a2dp.js
test/@yoda/bluetooth/a2dp-sink-test.js

* remove mute/unmute to prevent no sound.
* after interrupted by transient app, bluetooth music cannot resume play.
* error use of runtime.activity.exit().
* add flag to remember focus state to correct handle mute/unmute to avoid burst voice.

bluetooth: fix below bugs

---

runtime/client/ext-helper.js

Workaround for https://github.com/yodaos-project/ShadowNode/issues/373

app: force process to exit without any proceeding

---

runtime/services/otad/step.js
runtime/services/otad/wget.js
test/services/otad/step.test.js

Add missing step of fetching image size.

ota: fetch image size on downloading

---

apps/cloud-player/README.md
apps/cloud-player/app.js
apps/cloud-player/constant.js
apps/cloud-player/voice/tts-stream.js

cloud-player: implement new methods to retrieve player status

---

apps/cloud-player/app.js
apps/cloud-player/voice/player.js

cloud-player: broadcast multimedia status with tag

---

etc/yoda/system-config.json
runtime/lib/app-runtime.js
runtime/services/vuid/index.js

Optimized startup. and reset after startup complete.
example:
```js
// /etc/yoda/system-config.json
{
bootPriority: -19
}
```

feat: optimized startup

---

etc/manifest.json
runtime/services/otad/step.js
runtime/services/otad/wget.js

ota: configurable constraint on additional available space

---

.gitignore
packages/@yoda/system/index.js
packages/@yoda/system/src/SystemNative.cc
runtime/app/app-bridge.js
runtime/component/app-scheduler.js
test/component/app-scheduler/anr.test.js
test/testsets-ci.txt
test/testsets.txt
tools/build-yodart.sh

anr: use monotonic clock time

---

packages/@yodaos/speech-synthesis/src/pcm-player.cc
packages/@yodaos/speech-synthesis/src/pcm-player.h
packages/@yodaos/speech-synthesis/src/thr-pool.h

Fixes issues on `thr-pool#clear` suppressing upcoming `thr-pool#push` operation.
Picked from https://github.com/Rokid/aife-mutils/blob/c28017a11a5c08940098a42b487772db4f40341d/include/misc/thr-pool.h

speech-synthesis: update thr-pool

---

apps/bluetooth-music/app.js

bluetooth: remove `exit` to avoid app crash

---

etc/yoda/memory-sentinel.json
runtime/component/memory-sentinel.js
runtime/component/visibility.js
test/component/memory-sentinel/high-water-mark.test.js
test/component/memory-sentinel/index.test.js
test/component/memory-sentinel/low-free-memory.test.js
test/component/visibility/voice.test.js

memory-sentinel: broaden visibility restricts to all visible apps

---

apps/cloud-player/voice/player.js

cloud-player: emit multimedia cancel event on stop

---

packages/@yodaos/speech-synthesis/src/pcm-player.cc
packages/@yodaos/speech-synthesis/src/speech-synthesizer.cc
packages/@yodaos/speech-synthesis/src/speech-synthesizer.h

speech-synthesis: guard player while receiving data

---

apps/bluetooth-music/app.js

bluetooth: open before play if a2dp is not connected

---

packages/@yoda/oh-my-little-pony/index.js
runtime/services/otad/index.js
runtime/services/otad/wget.js
test/services/otad/wget.test.js

ota: gracefully exit on connection error of fetching image size

---

packages/@yoda/multimedia/mediaplayer.js
test/@yoda/multimedia/compat.test.js

mediaplayer: no-exception on getters

---

packages/@yodaos/voice-interface/index.js
runtime/client/ext-helper.js
test/@yodaos/voice-interface/bootstrap.js
test/@yodaos/voice-interface/index.test.js
test/@yodaos/voice-interface/voice-engine.js
test/testsets-ci.txt

voice-interface: engine operations

---

apps/cloud-player/README.md
apps/cloud-player/app.js
apps/cloud-player/constant.js
apps/cloud-player/voice/player.js

cloud-player: support seeking and speeding

---

apps/cloud-player/test/voice/player.test.js
apps/cloud-player/voice/player.js

cloud-player: broadcast player error event

---

packages/@yoda/input/src/InputNative.cc

Related: https://openai-corp.rokid.com/#/c/17341

input-event: monitor devices by /etc/input-event.conf

---

packages/@yoda/input/src/InputNative.cc

Reverts yodaos-project/yodart#828

Revert "input-event: monitor devices by /etc/input-event.conf"

---

apps/timer/README.md

timer: add readme

---

apps/bluetooth-music/README.md
apps/bluetooth-music/app.js
apps/bluetooth/README.md

- Change upload play status msg name and message format.
- Add upload playing music information.
- Add bluetooth-service & bluetooth-music README.md

bluetooth: add upload bluetooth music info and README

---

apps/timer/app.js
apps/timer/config.json
packages/@yodaos/application/vui/app-task.js

timer: fix timer crash issue

---

apps/bluetooth-music/README.md
apps/bluetooth-music/app.js

bluetooth: change upload status constants

---

test/testsets-ci.txt

test: skip flaky case @yodaos/voice-interface

---

apps/cloud-player/voice/player.js

cloud-player: delay first player start event to player prepared

---

apps/bluetooth-music/app.js

bluetooth: listen media control button event

---

packages/@yodaos/speech-synthesis/index.js
test/@yodaos/speech-synthesis/index.test.js

Fixes non specification aligned behavior.
Related: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/cancel

speech-synthesis: SpeechSynthesis#cancel should remove all utterance in queue

---

apps/bluetooth-music/README.md
apps/bluetooth-music/app.js
packages/@yoda/bluetooth/a2dp.js
test/@yoda/bluetooth/a2dp-sink-test.js

bluetooth: add fast-forward and rewind function

---

apps/bluetooth-music/app.js

fix bug: https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=22412

bluetooth: cancel disconnect after stop bluetooth music

---

apps/bluetooth/bluetooth-service.js
apps/bluetooth/strings.json

fix bug: https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=22433

bluetooth: add reopen case and more suitable TTS

---

apps/bluetooth/bluetooth-service.js
apps/bluetooth/resources.json

fix bug: https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=22428

bluetooth: correct bluetooth wifiless default TTS path

---

apps/timer/README.md
apps/timer/app.js

timer: handle local/cloud tts

---

packages/@yoda/bluetooth/a2dp-statemap.js

fix bug: https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&bugID=22597

bluetooth-a2dp: match reconnect message so can emit it to app

---

packages/@yoda/endoscope/README.md
packages/@yoda/endoscope/exporter/flora.js
packages/@yoda/endoscope/registry.js
test/@yoda/endoscope/bootstrap.js
test/@yoda/endoscope/exporter/flora.test.js
test/@yoda/endoscope/metric/counter.test.js
test/@yoda/endoscope/metric/enum.test.js
test/@yoda/endoscope/metric/histogram.test.js
test/testsets-ci.txt
test/testsets.txt

@yoda/endoscope: flora-exporter exports records with null labels

---

packages/@yoda/endoscope/metric/_metric.js
packages/@yoda/endoscope/metric/enum.js
test/@yoda/endoscope/metric/enum.test.js

endoscope: should pick non-enumerable label key-value pairs

---

packages/@yoda/endoscope/metric/_metric.js
test/@yoda/endoscope/metric/_metric.test.js

endoscope: tolerant null/undefined labels

---

.gitignore
.travis.yml
package.json
tools/build-yodart.sh
tools/coverage-instrument
tools/test

ci: coverage report

---

runtime/lib/component/flora.js

config duration of no voice interactive

smart close speech connection if no voice interactive

---

package.json
packages/@yoda/flora/src/cli-native.cc
tools/apt-get-install-deps.sh

PR-URL: https://github.com/yodaos-project/yodart/pull/876

build: use clang-format nom package

---

apps/cloudappclient/app.js

fix crash that caused by uncatch error

fix crash that caused by uncatch error

---

CMakeLists.txt
package.json
packages/@yodaos/speech-synthesis/src/speech-synthesizer.cc
runtime/app/app-bridge.js
runtime/app/default-launcher.js
runtime/app/executable-launcher.js
runtime/component/app-scheduler.js
runtime/services/lightd/index.js
tools/apt-get-install-deps.sh

* [2da5507f] - **versioning**: v8.2.1 (yorkie)
* [9bb8db3e] - **app-scheduler**: generate coredump on ANR (#875) (legendecas)
* [798d1d97] - **lightd**: do not init prepared audio if player.lightd.holdcon is 0 (#873) (Yazhong Liu)
* [d0f68273] - **build**: use clang-format nom package (#876) (legendecas)

versioning: v8.2.1

---

apps/cloudappclient/app.js
etc/yoda/system-config.json
package.json
packages/@yoda/flora/src/cli-native.cc
packages/@yoda/multimedia/src/MediaPlayer.cc
packages/@yoda/system/src/SystemNative.cc
runtime/lib/app-runtime.js
runtime/lib/component/flora.js
runtime/services/vuid/index.js
test/runtime/init/index.test.js
tools/apt-get-install-deps.sh

* [71b3c42b] - **cloudappclient**: fix crash that caused by uncatch error (#874) (sudo)
* [b72f4221] - **build**: use clang-format npm package (legendecas)
* [07be4160] - **speech**: smart close speech connection if no voice interactive (#870) (mingzc0508)
* [dafd571b] - **feat**: introduce the bootPriority config to improve bootstrapping (#794) (sudo)
* [7e6dc7a9] - **runtime**: fix skill stack error (#795) (Jim Tang)
* [28586b6c] - **system**: move glibc specific API to conditional build macro block (#778) (zhanghuan0910)
* [35ffbdd3] - wifi switch mode sync support (#769) (sudo)
* [0d9a63a9] - **ttsd**: should not emit event after emit termination event (#760) (sudo)
* [3b6ed97c] - **runtime**: fix unbind syntax error (#761) (sudo)

Proposal v7.38.4

---

packages/@yoda/oh-my-little-pony/index.js
runtime/client/ext-app-entry.js
runtime/client/ext-helper.js

Dump stacktrace like coredump but for JavaScript🎉

pony: save application report in app data dir

---

apps/composition-de-voix/app.js

Refs: https://bug.rokid-inc.com/zentaopms/www/index.php?m=bug&f=view&t=html&id=22876

comp-de-voix: destroy all other app on start

---

packages/@yoda/oh-my-little-pony/index.js
packages/@yoda/util/fs.js
test/@yoda/oh-my-little-pony/executor.js
test/@yoda/oh-my-little-pony/index.test.js
test/@yoda/oh-my-little-pony/stacktrace.js
test/testsets-local.txt

This adds the unit-tests and only land pony-related changes on v7.x-staging.

pony: backport #883 into v7.x-staging partially

---

apps/cloudappclient/app.js

catch error on property set

---

apps/cloudappclient/app.js
apps/composition-de-voix/app.js
packages/@yoda/oh-my-little-pony/index.js
packages/@yoda/util/fs.js
runtime/lib/component/turen.js
test/@yoda/oh-my-little-pony/executor.js
test/@yoda/oh-my-little-pony/index.test.js
test/@yoda/oh-my-little-pony/stacktrace.js
test/component/turen/reset-awaken.test.js
test/testsets-local.txt
test/testsets.txt

Proposal v7.38.5

---

runtime/services/otad/step.js

ota: clean up images during lock acquired procedure
